// Auto-generated from CORRELACAO_TRIBMUN_TRIBNAC_RIBEIRAOPRETO.csv
// Atividades Municipais de Ribeirao Preto

export interface AtividadeMunicipal {
  codigo: string;
  descricao: string;
  aliquota: string;
}

export const ATIVIDADES_MUNICIPAIS: AtividadeMunicipal[] = [
  { codigo: '1000200', descricao: 'B) Demais Serv. Qualificados, Inclusive Nivel Superior', aliquota: '0%' },
  { codigo: '100101', descricao: 'Agenciamento, Corretagem ou Intermediacao de Cambio.', aliquota: '2%' },
  { codigo: '10010199', descricao: 'Agenciamento, Corretagem ou Intermediacao de Cambio.', aliquota: '0%' },
  { codigo: '100102', descricao: 'Agenciamento, Corretagem ou Intermediacao de Seguros.', aliquota: '2%' },
  { codigo: '10010299', descricao: 'Agenciamento, Corretagem ou Intermediacao de Seguros.', aliquota: '0%' },
  { codigo: '100103', descricao: 'Agenciamento, Corretagem ou Intermediacao de Cartoes de Credito.', aliquota: '2%' },
  { codigo: '10010399', descricao: 'Agenciamento, Corretagem ou Intermediacao de Cartoes de Credito.', aliquota: '0%' },
  { codigo: '100104', descricao: 'Agenciamento, Corretagem ou Intermediacao de Planos de Saude.', aliquota: '2%' },
  { codigo: '10010499', descricao: 'Agenciamento, Corretagem ou Intermediacao de Planos de Saude.', aliquota: '0%' },
  { codigo: '100105', descricao: 'Agenciamento, Corretagem ou Intermediacao de Planos de Previdencia Privada', aliquota: '2%' },
  { codigo: '10010599', descricao: 'Agenciamento, Corretagem ou Intermediacao de Planos de Previdencia Privada', aliquota: '0%' },
  { codigo: '100200', descricao: 'Agenciamento, Corretagem ou Intermediacao de Titulo em Geral, Valores Mobiliarios Contratos Quaisquer e Consorcios.', aliquota: '2%' },
  { codigo: '100201', descricao: 'Agenciamento de Titulos em Geral, Valores Mobiliarios Econtratos Quaisquer.', aliquota: '2%' },
  { codigo: '10020199', descricao: 'Agenciamento de Titulos em Geral, Valores Mobiliarios Econtratos Quaisquer.', aliquota: '0%' },
  { codigo: '100202', descricao: 'Corretagem de Titulos em Geral, Valores Mobiliarios e Contratos Quaisquer.', aliquota: '2%' },
  { codigo: '10020299', descricao: 'Corretagem de Titulos em Geral, Valores Mobiliarios e Contratos Quaisquer.', aliquota: '0%' },
  { codigo: '100203', descricao: 'Intermediacao de Titulos em Geral, Valores Mobiliarios e Contratos Quaisquer.', aliquota: '2%' },
  { codigo: '10020399', descricao: 'Intermediacao de Titulos em Geral, Valores Mobiliarios e Contratos Quaisquer.', aliquota: '0%' },
  { codigo: '100301', descricao: 'Agenciamento, Corretagem ou Intermediacao de Direitos de Propriedade Industrial, (inclusive Marcas e Patentes) .', aliquota: '2%' },
  { codigo: '10030199', descricao: 'Agenciamento, Corretagem ou Intermediacao de Direitos de Propriedade Industrial, (inclusive Marcas e Patentes) .', aliquota: '0%' },
  { codigo: '100302', descricao: 'Agenciamento, Corretagem ou Intermediacao de Direitos de Propriedade Artistica', aliquota: '2%' },
  { codigo: '100303', descricao: 'Agenciamento, Corretagem ou Intermediacao de Direitos de Propriedade Literaria', aliquota: '2%' },
  { codigo: '100401', descricao: 'Agenciamento, Corretagem ou Intermediacao de Contratos de Arrendamento Mercantil (leasing)', aliquota: '2%' },
  { codigo: '100402', descricao: 'Agenciamento, Corretagem ou Intermediacao de Contratos de Franquia (franchising)', aliquota: '2%' },
  { codigo: '100403', descricao: 'Agenciamento, Corretagem ou Intermediacao de Contratos de Faturizacao(factoring)', aliquota: '2%' },
  { codigo: '10040399', descricao: 'Agenciamento, Corretagem ou Intermediacao de Contratos de Faturizacao(factoring)', aliquota: '0%' },
  { codigo: '100501', descricao: 'Agenciamento, Corretagem ou Intermediacao de Veiculos Automotores.', aliquota: '2%' },
  { codigo: '10050199', descricao: 'Agenciamento, Corretagem ou Intermediacao de Veiculos Automotores.', aliquota: '0%' },
  { codigo: '100502', descricao: 'Agenciamento, Corretagem ou Intermediacao de Imoveis.', aliquota: '2%' },
  { codigo: '10050299', descricao: 'Agenciamento, Corretagem ou Intermediacao de Imoveis.', aliquota: '0%' },
  { codigo: '100503', descricao: 'Agenciamento, Corretagem ou Intermediacao de Insumos ou Produtos Agropecuarios (comodites)', aliquota: '2%' },
  { codigo: '10050399', descricao: 'Agenciamento, Corretagem ou Intermediacao de Insumos ou Produtos Agropecuarios (comodites)', aliquota: '0%' },
  { codigo: '100504', descricao: 'Agenciamento, Corretagem ou Intermediacao de Outros Bens Moveis ou Imoveis, Nao Abrangidos em Outros Itens ou Subitens, Inclusive Aqueles Realizados no Ambito de Bolsas de Mercadorias e Futuros, Por Quaisquer Meios.', aliquota: '2%' },
  { codigo: '10050499', descricao: 'Agenciamento, Corretagem ou Intermediacao de Outros Bens Moveis ou Imoveis, Nao Abrangidos em Outros Itens ou Subitens, Inclusive Aqueles Realizados no Ambito de Bolsas de Mercadorias e Futuros, Por Quaisquer Meios.', aliquota: '0%' },
  { codigo: '100600', descricao: 'Agenciamento Maritimo.', aliquota: '2%' },
  { codigo: '100700', descricao: 'Agenciamento de Noticias.', aliquota: '2%' },
  { codigo: '100800', descricao: 'Agenciamento de Publicidade e Propaganda, Inclusive O Agenciamento de Veiculac AO Por Quaisquer Meios.', aliquota: '2%' },
  { codigo: '10080099', descricao: 'Agenciamento de Publicidade e Propaganda, Inclusive O Agenciamento de Veiculac AO Por Quaisquer Meios.', aliquota: '0%' },
  { codigo: '100901', descricao: 'Representacao de Qualquer Natureza, Inclusive Comercial', aliquota: '2%' },
  { codigo: '10090199', descricao: 'Representacao de Qualquer Natureza, Inclusive Comercial', aliquota: '0%' },
  { codigo: '100902', descricao: 'Representante Comercial Autonomo', aliquota: '2%' },
  { codigo: '10090299', descricao: 'Representante Comercial Autonomo', aliquota: '0%' },
  { codigo: '100903', descricao: 'Telemarketing, Teleatendimento, Televendas e Congeneres.', aliquota: '2%' },
  { codigo: '10090399', descricao: 'Telemarketing, Teleatendimento, Televendas e Congeneres.', aliquota: '0%' },
  { codigo: '10100', descricao: 'Analise e Desenvolvimento de Sistemas.', aliquota: '2%' },
  { codigo: '101000', descricao: 'Distribuicao de Bens de Terceiros.', aliquota: '2%' },
  { codigo: '10100099', descricao: 'Distribuicao de Bens de Terceiros.', aliquota: '0%' },
  { codigo: '1010099', descricao: 'Analise e Desenvolvimento de Sistemas.', aliquota: '0%' },
  { codigo: '10200', descricao: 'Programacao.', aliquota: '2%' },
  { codigo: '1020099', descricao: 'Programacao.', aliquota: '0%' },
  { codigo: '10300', descricao: 'Processamento de Dados e Congeneres.', aliquota: '2%' },
  { codigo: '1030099', descricao: 'Processamento de Dados e Congeneres.', aliquota: '0%' },
  { codigo: '10400', descricao: 'Elaboracao de Programas de Computadores, Inclusive de Jogos Eletronicos.', aliquota: '2%' },
  { codigo: '10500', descricao: 'Licenciamento ou Cessao de Direito de Uso de Programas de Computacao.', aliquota: '2%' },
  { codigo: '10600', descricao: 'Assessoria e Consultoria em Informatica.', aliquota: '2%' },
  { codigo: '1060099', descricao: 'Assessoria e Consultoria em Informatica.', aliquota: '0%' },
  { codigo: '10700', descricao: 'Suporte Tecnico em Informatica, Inclusive Instalacao, Configuracao', aliquota: '2%' },
  { codigo: '1070099', descricao: 'Suporte Tecnico em Informatica, Inclusive Instalacao, Configuracao', aliquota: '0%' },
  { codigo: '10801', descricao: 'Planejamento, Confeccao, Manutencao e Atualizacao de Paginas Eletronicas.', aliquota: '2%' },
  { codigo: '1080199', descricao: 'Planejamento, Confeccao, Manutencao e Atualizacao de Paginas Eletronicas.', aliquota: '0%' },
  { codigo: '10802', descricao: 'Provedor de Internet Disponibilização, Sem Cessão Definitiva, de Conteúdos de Áudio, Vídeo, Imagem e Texto Por Meio da Internet, Respeitada A Imunidade de', aliquota: '2%' },
  { codigo: '10900', descricao: 'Livros, Jornais e Periódicos (exceto A Distribuição de Conteúdos Pelas Prestadoras de Serviço de Acesso Condicionado, de Que Trata A Lei no 12. 485, de 12 de Setembro de 2011, Sujeita AO Icms) .', aliquota: '2%' },
  { codigo: '110101', descricao: 'Guarda e Estacionamento de Veiculos Terrestres Automotores (estabelelcimento) .', aliquota: '4%' },
  { codigo: '11010199', descricao: 'Guarda e Estacionamento de Veiculos Terrestres Automotores (estabelelcimento) .', aliquota: '0%' },
  { codigo: '110102', descricao: 'Guardadores de Veiculos em Vias Publicas', aliquota: '4%' },
  { codigo: '11010299', descricao: 'Guardadores de Veiculos em Vias Publicas', aliquota: '0%' },
  { codigo: '110103', descricao: 'Guarda e Estacionamento Tipo \'valet Service\'', aliquota: '4%' },
  { codigo: '11010399', descricao: 'Guarda e Estacionamento Tipo \'valet Service\'', aliquota: '0%' },
  { codigo: '110104', descricao: 'Guarda e Estacionamento de Aeronaves.', aliquota: '4%' },
  { codigo: '110105', descricao: 'Guarda e Estacionamento de Embarcacoes.', aliquota: '4%' },
  { codigo: '110201', descricao: 'Vigilância, Segurança de Bens, Pessoas e Semoventes.', aliquota: '2%' },
  { codigo: '11020199', descricao: 'Vigilância, Segurança de Bens, Pessoas e Semoventes.', aliquota: '0%' },
  { codigo: '110202', descricao: 'Guarda Noturno, Vigilante', aliquota: '2%' },
  { codigo: '11020299', descricao: 'Guarda Noturno, Vigilante', aliquota: '0%' },
  { codigo: '110203', descricao: 'Monitoramento de Bens, Pessoas e Semoventes.', aliquota: '2%' },
  { codigo: '110300', descricao: 'Escolta, Inclusive de Veiculos e Cargas.', aliquota: '2%' },
  { codigo: '110401', descricao: 'Armazenamento de Bens de Qualquer Especie.', aliquota: '2%' },
  { codigo: '110402', descricao: 'Armazenamento ( Frigorificos )', aliquota: '2%' },
  { codigo: '110403', descricao: 'Deposito de Bens de Qualquer Especie ( Exceto Banco )', aliquota: '2%' },
  { codigo: '110404', descricao: 'Carga, Descarga de Bens de Qualquer Especie', aliquota: '2%' },
  { codigo: '11040499', descricao: 'Carga, Descarga de Bens de Qualquer Especie', aliquota: '0%' },
  { codigo: '110405', descricao: 'Arrumacao e Guarda de Bens de Qualquer Especie.', aliquota: '2%' },
  { codigo: '110501', descricao: 'Serviços relacionados ao monitoramento e rastreamento a distância, em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação ou movimento, realizados por meio de telefonia móvel, transmissão de satélites, rádio ou qualquer outro meio, inclusive pelas empresas de Tecnologia da Informação Veicular, independentemente de o prestador de serviços ser proprietário ou não da infraestrutura de telecomunicações que utiliza', aliquota: '2%' },
  { codigo: '120100', descricao: 'Espetaculos Teatrais.', aliquota: '3.5%' },
  { codigo: '120200', descricao: 'Exibicoes Cinematograficas.', aliquota: '2%' },
  { codigo: '120300', descricao: 'Espetaculos Circenses.', aliquota: '3.5%' },
  { codigo: '120400', descricao: 'Programas de Auditorio.', aliquota: '3.5%' },
  { codigo: '120500', descricao: 'Parques de Diversoes, Centros de Lazer e Congeneres.', aliquota: '3.5%' },
  { codigo: '120601', descricao: 'Boates, Night Clube.', aliquota: '4%' },
  { codigo: '120602', descricao: 'Taxi - Dancing, Drive - IN e Congeneres.', aliquota: '4%' },
  { codigo: '120701', descricao: 'Shows, Operas, Concertos, Recitais, Festivais e Congeneres', aliquota: '2%' },
  { codigo: '120702', descricao: 'Ballet, Dancas, Desfiles', aliquota: '2%' },
  { codigo: '120703', descricao: 'Bailes', aliquota: '2%' },
  { codigo: '120801', descricao: 'Feiras, Exposicoes, Congressos e Congeneres.', aliquota: '4%' },
  { codigo: '120802', descricao: 'Exposicoes Com Cobranca de Ingressos', aliquota: '4%' },
  { codigo: '120901', descricao: 'Bilhares', aliquota: '3.5%' },
  { codigo: '120902', descricao: 'Boliches', aliquota: '3.5%' },
  { codigo: '120903', descricao: 'Diversoes Eletronicas ou Nao.', aliquota: '3.5%' },
  { codigo: '120904', descricao: 'Futebol de Mesa ( Pebolim )', aliquota: '3.5%' },
  { codigo: '120905', descricao: 'Carteado, Domino, Vispora e Outros Tipos de Diversoes.', aliquota: '3.5%' },
  { codigo: '121000', descricao: 'Corridas e Competicoes de Animais.', aliquota: '3.5%' },
  { codigo: '121100', descricao: 'Competicoes Esportivas ou de Destreza Fisica ou Intelectual, Com ou Sem A Parti Cipacao do Espectador.', aliquota: '3.5%' },
  { codigo: '121200', descricao: 'Execucao de Musica. ( Individual ou Por Conjunto ) .', aliquota: '4%' },
  { codigo: '12120099', descricao: 'Execucao de Musica. ( Individual ou Por Conjunto ) .', aliquota: '0%' },
  { codigo: '121300', descricao: 'Producao, Mediante ou Sem Encomenda Previa, de Eventos, Espetaculos, Entrevistas, Shows, Ballet, Dancas, Desfiles, Bailes, Teatros, Operas, Concertos, Recitaisfestivais e Congeneres, Inclusive Programas de Televisao, Materias Jornalisticasou Publicitarias.', aliquota: '4%' },
  { codigo: '121400', descricao: 'Fornecimento de Musica Para Ambientes Fechados ou Nao, Mediante Transmissao Por Qualquer Processo.', aliquota: '3.5%' },
  { codigo: '121500', descricao: 'Desfiles de Blocos Carnavalescos ou Folcloricos, Trios Eletricos e Congeneres.', aliquota: '3.5%' },
  { codigo: '121600', descricao: 'Exibicao de Filmes, Entrevistas, Musicais, Espetaculos, Shows, Concertos, Desfil Es, Operas, Compet. Esportivas, Destreza Intelectual ou Congeneres.', aliquota: '3.5%' },
  { codigo: '121700', descricao: 'Recreacao e Animacao, Inclusive em Festas e Eventos de Qualquer Natureza.', aliquota: '4%' },
  { codigo: '12170099', descricao: 'Recreacao e Animacao, Inclusive em Festas e Eventos de Qualquer Natureza.', aliquota: '0%' },
  { codigo: '130200', descricao: 'Fonografia ou Gravacao de Sons, Inclusive Trucagem, DU - Blagem, Mixagem e Congen Eres.', aliquota: '3%' },
  { codigo: '13020099', descricao: 'Fonografia ou Gravacao de Sons, Inclusive Trucagem, DU - Blagem, Mixagem e Congen Eres.', aliquota: '0%' },
  { codigo: '130301', descricao: 'Fotografia.', aliquota: '3%' },
  { codigo: '13030199', descricao: 'Fotografia.', aliquota: '0%' },
  { codigo: '130302', descricao: 'Producao Audio - Visual.', aliquota: '3%' },
  { codigo: '13030299', descricao: 'Producao Audio - Visual.', aliquota: '0%' },
  { codigo: '130303', descricao: 'Revelacao, Ampliacao, Copia, Reproducao, Trucagem e Congeneres.', aliquota: '3%' },
  { codigo: '13030399', descricao: 'Revelacao, Ampliacao, Copia, Reproducao, Trucagem e Congeneres.', aliquota: '0%' },
  { codigo: '130304', descricao: 'Fotografia, Cinematografia ou Outros, de Registro de Eventos (casamentos, Formatu Ras, Festas, Recepcoes, Solenidades e Congeneres) .', aliquota: '3%' },
  { codigo: '13030499', descricao: 'Fotografia, Cinematografia ou Outros, de Registro de Eventos (casamentos, Formatu Ras, Festas, Recepcoes, Solenidades e Congeneres) .', aliquota: '0%' },
  { codigo: '130399', descricao: '(0%) - 13.03  Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres.', aliquota: '0%' },
  { codigo: '130401', descricao: 'Reprografia, ( Copia de Documentos ) .', aliquota: '2%' },
  { codigo: '130402', descricao: 'Microfilmagem e Digitalizacao.', aliquota: '2%' },
  { codigo: '130501', descricao: 'Composição Gráfica, Inclusive Confecção de Impressos Gráficos, Exceto SE Destinados A Posterior Operação de Comercialização ou Industrialização, Ainda Que Incorporados, de Qualquer Forma, A Outra Mercadoria Que Deva Ser Objeto de Posterior Circulação, Tais Como Bulas, Rótulos, Etiquetas, Caixas, Cartuchos, Embalagens e Manuais Técnicos e de Instrução, Quando Ficarão Sujeitos AO Icms.', aliquota: '2%' },
  { codigo: '130502', descricao: 'Fotocomposicao', aliquota: '2%' },
  { codigo: '130503', descricao: 'Clicheria, Zincografia, Litografia, Fotolitografia.', aliquota: '2%' },
  { codigo: '130504', descricao: 'Artes Graficas, Tipografia', aliquota: '2%' },
  { codigo: '130505', descricao: 'Serigrafia (silk Screen)', aliquota: '2%' },
  { codigo: '1401001', descricao: '(Cooperativas) 14.01  Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos, equipamentos, motores, elevadores ou de qualquer objeto (exceto peças e partes empregadas, que ficam sujeitas ao ICMS).', aliquota: '2.5%' },
  { codigo: '140101', descricao: 'Lubrificacao de Maquinas, Aparelhos e Equipamentos, (exceto Pecas e Partes e Mpregadas, Sujeitas AO Icms) .', aliquota: '2.5%' },
  { codigo: '140102', descricao: 'Limpeza de Maquinas, Aparelhos e Equipamentos', aliquota: '2.5%' },
  { codigo: '140103', descricao: 'Lustracao de Maquinas, Aparelhos e Equipamentos', aliquota: '2.5%' },
  { codigo: '140104', descricao: 'Lustrador ( Isento )', aliquota: '2.5%' },
  { codigo: '14010499', descricao: 'Lustrador ( Isento )', aliquota: '0%' },
  { codigo: '140105', descricao: 'Revisao, Carga e Recarga de Maquinas, Aparelhos e Equipamentos', aliquota: '2.5%' },
  { codigo: '14010599', descricao: 'Revisao, Carga e Recarga de Maquinas, Aparelhos e Equipamentos', aliquota: '0%' },
  { codigo: '140106', descricao: 'Restauracao de Quaisquer Objetos', aliquota: '2.5%' },
  { codigo: '14010699', descricao: 'Restauracao de Quaisquer Objetos', aliquota: '0%' },
  { codigo: '140107', descricao: 'Conserto, Manutencao e Conservacao de Quaisquer Objetos', aliquota: '2.5%' },
  { codigo: '14010799', descricao: 'Conserto, Manutencao e Conservacao de Quaisquer Objetos', aliquota: '0%' },
  { codigo: '140108', descricao: 'Conserto, Restauracao de Sapatos.', aliquota: '2.5%' },
  { codigo: '14010899', descricao: 'Conserto, Restauracao de Sapatos.', aliquota: '0%' },
  { codigo: '140109', descricao: 'Conserto, Restauracao de Joias, Relogios e Congeneres', aliquota: '2.5%' },
  { codigo: '14010999', descricao: 'Conserto, Restauracao de Joias, Relogios e Congeneres', aliquota: '0%' },
  { codigo: '140110', descricao: 'Conserto, Restauracao de Oculos ( Oticas )', aliquota: '2.5%' },
  { codigo: '14011099', descricao: 'Conserto, Restauracao de Oculos ( Oticas )', aliquota: '0%' },
  { codigo: '140111', descricao: 'Conserto, Restauracao de Aparel. Eletricos, Eletronicos', aliquota: '2.5%' },
  { codigo: '14011199', descricao: 'Conserto, Restauracao de Aparel. Eletricos, Eletronicos', aliquota: '0%' },
  { codigo: '140112', descricao: 'Conserto, Restauracao de Eletrodomesticos.', aliquota: '2.5%' },
  { codigo: '14011299', descricao: 'Conserto, Restauracao de Eletrodomesticos.', aliquota: '0%' },
  { codigo: '140113', descricao: 'Conserto, Restauracao de Instrumentos Musicais', aliquota: '2.5%' },
  { codigo: '14011399', descricao: 'Conserto, Restauracao de Instrumentos Musicais', aliquota: '0%' },
  { codigo: '140114', descricao: 'Conserto, Restauracao de Maquinas Agricolas e Congener.', aliquota: '2.5%' },
  { codigo: '140115', descricao: 'Conserto, Restauracao de Aparelhos Odontologicos, Hosp., Ortopedicos, Laboratori Ais. .', aliquota: '2.5%' },
  { codigo: '14011599', descricao: 'Conserto, Restauracao de Aparelhos Odontologicos, Hosp., Ortopedicos, Laboratori Ais. .', aliquota: '0%' },
  { codigo: '140116', descricao: 'Conserto, Restauracao de Maquinas e Equipamentos Para Escritorio. - - -', aliquota: '2.5%' },
  { codigo: '140117', descricao: 'Conserto Por Soldagem.', aliquota: '2.5%' },
  { codigo: '14011799', descricao: 'Conserto Por Soldagem.', aliquota: '0%' },
  { codigo: '140118', descricao: 'Conserto, Restauracao de Computadores e Similares', aliquota: '2.5%' },
  { codigo: '14011899', descricao: 'Conserto, Restauracao de Computadores e Similares', aliquota: '0%' },
  { codigo: '140119', descricao: 'Conserto, Restauracao de Brinquedos em Geral', aliquota: '2.5%' },
  { codigo: '140120', descricao: 'Conserto, Restauracao de Aparelhos Equipamentos Indus - Triais, Graficos, Etc', aliquota: '2.5%' },
  { codigo: '14012099', descricao: 'Conserto, Restauracao de Aparelhos Equipamentos Indus - Triais, Graficos, Etc', aliquota: '0%' },
  { codigo: '140121', descricao: 'Conserto, Restauracao de Elevadores', aliquota: '2.5%' },
  { codigo: '140122', descricao: 'Conserto, Restauracao de Aparelho de AR Condicionado e Refrigeraã¿o.', aliquota: '2.5%' },
  { codigo: '14012299', descricao: 'Conserto, Restauracao de Aparelho de AR Condicionado e Refrigeraã¿o.', aliquota: '0%' },
  { codigo: '140123', descricao: 'Conserto, Restauracao de Letreiros, Luminosos em Geral.', aliquota: '2.5%' },
  { codigo: '140124', descricao: 'Conserto, Restauracao de Moveis em Geral.', aliquota: '2.5%' },
  { codigo: '14012499', descricao: 'Conserto, Restauracao de Moveis em Geral.', aliquota: '0%' },
  { codigo: '140125', descricao: 'Conserto, Restauracao de Bicicletas, Pecas e Similares', aliquota: '2.5%' },
  { codigo: '14012599', descricao: 'Conserto, Restauracao de Bicicletas, Pecas e Similares', aliquota: '0%' },
  { codigo: '140126', descricao: 'Conserto de Veiculos ( Parte Eletrica )', aliquota: '2.5%' },
  { codigo: '14012699', descricao: 'Conserto de Veiculos ( Parte Eletrica )', aliquota: '0%' },
  { codigo: '140127', descricao: 'Conserto de Motocicletas e Similares', aliquota: '2.5%' },
  { codigo: '14012799', descricao: 'Conserto de Motocicletas e Similares', aliquota: '0%' },
  { codigo: '140128', descricao: 'Oficina Mecanica.', aliquota: '2.5%' },
  { codigo: '14012899', descricao: 'Oficina Mecanica.', aliquota: '0%' },
  { codigo: '140129', descricao: 'Lubrificacao, Revisao e Lavagem de Veiculos (postos)', aliquota: '2.5%' },
  { codigo: '140130', descricao: 'Lavagem, Lubrificacao em Veiculos (outros) .', aliquota: '2.5%' },
  { codigo: '14013099', descricao: 'Lavagem, Lubrificacao em Veiculos (outros) .', aliquota: '0%' },
  { codigo: '140131', descricao: 'Alinhamento e Balanceamento de Automoveis.', aliquota: '2.5%' },
  { codigo: '14013199', descricao: 'Alinhamento e Balanceamento de Automoveis.', aliquota: '0%' },
  { codigo: '140132', descricao: 'Borracharia', aliquota: '2.5%' },
  { codigo: '14013299', descricao: 'Borracharia', aliquota: '0%' },
  { codigo: '140133', descricao: 'Blindagens em Geral', aliquota: '2.5%' },
  { codigo: '140134', descricao: 'Conserto de Radiadores de Veiculos Automotores.', aliquota: '2.5%' },
  { codigo: '140135', descricao: 'Conserto de Direcao de Veiculos Automotores.', aliquota: '2.5%' },
  { codigo: '140136', descricao: 'Conserto de Cambio de Veiculos Automotores.', aliquota: '2.5%' },
  { codigo: '140137', descricao: 'Conserto de Vidros Eletricos de Veiculos Automotores.', aliquota: '2.5%' },
  { codigo: '140138', descricao: 'Conserto de Tapecaria de Veiculos Automotores.', aliquota: '2.5%' },
  { codigo: '140139', descricao: 'Conserto de Aeronaves ou Suas Partes.', aliquota: '2.5%' },
  { codigo: '14013999', descricao: 'Conserto de Aeronaves ou Suas Partes.', aliquota: '0%' },
  { codigo: '140200', descricao: 'Assistencia Tecnica.', aliquota: '0%' },
  { codigo: '140201', descricao: 'Assistencia Tecnica', aliquota: '2.5%' },
  { codigo: '14020199', descricao: 'Assistencia Tecnica', aliquota: '0%' },
  { codigo: '140202', descricao: 'Contrato de Garantia de Assistencia Tecnica, Exceto Pelo Fabricante. - - -', aliquota: '2.5%' },
  { codigo: '140300', descricao: 'Retifica e Recondicionamento de Motores (exceto Pecas e Partes Empregadas, Que Ficam Sujeitas AO Icms) .', aliquota: '2.5%' },
  { codigo: '14030099', descricao: 'Retifica e Recondicionamento de Motores (exceto Pecas e Partes Empregadas, Que Ficam Sujeitas AO Icms) .', aliquota: '0%' },
  { codigo: '140400', descricao: 'Recauchutagem ou Regeneracao de Pneus.', aliquota: '2%' },
  { codigo: '140501', descricao: 'Recondicionamento de Objetos Quaisquer, Afiacao.', aliquota: '2.5%' },
  { codigo: '14050199', descricao: 'Recondicionamento de Objetos Quaisquer, Afiacao.', aliquota: '0%' },
  { codigo: '140502', descricao: 'Acondicionamento de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '140503', descricao: 'Pintura de Objetos Quaisquer (placas, Paineis, Quadros. . )', aliquota: '2.5%' },
  { codigo: '14050399', descricao: 'Pintura de Objetos Quaisquer (placas, Paineis, Quadros. . )', aliquota: '0%' },
  { codigo: '140504', descricao: 'Pintura de Veiculos', aliquota: '2.5%' },
  { codigo: '14050499', descricao: 'Pintura de Veiculos', aliquota: '0%' },
  { codigo: '140505', descricao: 'Beneficiamento de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '14050599', descricao: 'Beneficiamento de Objetos Quaisquer', aliquota: '0%' },
  { codigo: '140506', descricao: 'Lavagem de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '14050699', descricao: 'Lavagem de Objetos Quaisquer', aliquota: '0%' },
  { codigo: '140507', descricao: 'Secagem de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '140508', descricao: 'Tingimento de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '140509', descricao: 'Galvanoplastia de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '140510', descricao: 'Anodizacao de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '140511', descricao: 'Corte, Recorte, de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '140512', descricao: 'Polimento e Cristalizacao de Quaisquer Objetos', aliquota: '2.5%' },
  { codigo: '140513', descricao: 'Plastificacao e Congeneres, de Objetos Quaisquer', aliquota: '2.5%' },
  { codigo: '14051399', descricao: 'Plastificacao e Congeneres, de Objetos Quaisquer', aliquota: '0%' },
  { codigo: '140514', descricao: 'Tornearia e Usinagem', aliquota: '2.5%' },
  { codigo: '14051499', descricao: 'Tornearia e Usinagem', aliquota: '0%' },
  { codigo: '140515', descricao: 'Jateamento', aliquota: '2.5%' },
  { codigo: '140516', descricao: 'Instalacao de Acessorios em Veiculos Automotores', aliquota: '2.5%' },
  { codigo: '14051699', descricao: 'Instalacao de Acessorios em Veiculos Automotores', aliquota: '0%' },
  { codigo: '140517', descricao: 'Costura, Acabamento de Objetos Quaisquer.', aliquota: '2.5%' },
  { codigo: '140599', descricao: 'Outros', aliquota: '2.5%' },
  { codigo: '140601', descricao: 'Instalacao e Montagem de Aparelhos, Maquinas e Equipamentos, Prestados AO Usuario Final, Exclusivamente Com Material Por Ele Fornecido.', aliquota: '2.5%' },
  { codigo: '14060199', descricao: 'Instalacao e Montagem de Aparelhos, Maquinas e Equipamentos, Prestados AO Usuario Final, Exclusivamente Com Material Por Ele Fornecido.', aliquota: '0%' },
  { codigo: '140602', descricao: 'Montagem Industrial, Prestados AO Usuario Final, Exclu - Sivamente Com Material P OR Ele Fornecido.', aliquota: '2.5%' },
  { codigo: '140603', descricao: 'Montagem de Oculos Para O Usuario Final (otica) .', aliquota: '2.5%' },
  { codigo: '14060399', descricao: 'Montagem de Oculos Para O Usuario Final (otica) .', aliquota: '0%' },
  { codigo: '140700', descricao: 'Colocacao de Molduras e Congeneres.', aliquota: '2%' },
  { codigo: '140800', descricao: 'Encadernacao, Gravacao e Douracao de Livros, Revistas e Congeneres.', aliquota: '2%' },
  { codigo: '140901', descricao: 'Alfaiataria, Quando O Material For Fornecido Pelo Usua - Rio Final, Exceto Aviame Nto.', aliquota: '2.5%' },
  { codigo: '14090199', descricao: 'Alfaiataria, Quando O Material For Fornecido Pelo Usua - Rio Final, Exceto Aviame Nto.', aliquota: '0%' },
  { codigo: '140902', descricao: 'Costura (costureiras, Etc. ) Quando O Material For For - Necido Pelo Usuario Fina L, Exceto Aviamento.', aliquota: '2.5%' },
  { codigo: '14090299', descricao: 'Costura (costureiras, Etc. ) Quando O Material For For - Necido Pelo Usuario Fina L, Exceto Aviamento.', aliquota: '0%' },
  { codigo: '140903', descricao: 'Modista', aliquota: '2.5%' },
  { codigo: '14090399', descricao: 'Modista', aliquota: '0%' },
  { codigo: '141001', descricao: 'Tinturaria', aliquota: '2.5%' },
  { codigo: '141002', descricao: 'Lavanderia.', aliquota: '2.5%' },
  { codigo: '141100', descricao: 'Tapecaria e Reforma de Estofamentos em Geral.', aliquota: '3%' },
  { codigo: '14110099', descricao: 'Tapecaria e Reforma de Estofamentos em Geral.', aliquota: '0%' },
  { codigo: '141200', descricao: 'Funilaria e Lanternagem.', aliquota: '2.5%' },
  { codigo: '14120099', descricao: 'Funilaria e Lanternagem.', aliquota: '0%' },
  { codigo: '141301', descricao: 'Carpintaria (instalacao, Montagem ou Conserto de Bens Moveis)', aliquota: '2.5%' },
  { codigo: '14130199', descricao: 'Carpintaria (instalacao, Montagem ou Conserto de Bens Moveis)', aliquota: '0%' },
  { codigo: '141302', descricao: 'Serralheria (instalacao, Montagem ou Conserto de Bens Moveis)', aliquota: '2.5%' },
  { codigo: '14130299', descricao: 'Serralheria (instalacao, Montagem ou Conserto de Bens Moveis)', aliquota: '0%' },
  { codigo: '141303', descricao: 'Marcenaria (instalacao, Montagem ou Conserto de Bens Moveis)', aliquota: '2.5%' },
  { codigo: '14130399', descricao: 'Marcenaria (instalacao, Montagem ou Conserto de Bens Moveis)', aliquota: '0%' },
  { codigo: '141401', descricao: 'Guincho Intramunicipal', aliquota: '3%' },
  { codigo: '141402', descricao: 'Guindaste e Içamento', aliquota: '3%' },
  { codigo: '141515', descricao: 'Jateamento', aliquota: '0%' },
  { codigo: '150101', descricao: 'Administracao de Fundos Quaisquer.', aliquota: '5%' },
  { codigo: '150102', descricao: 'Organizacao e Administracao de Consorcio.', aliquota: '5%' },
  { codigo: '150103', descricao: 'Administracao de Cartoes de Credito, Debito e Congeneres.', aliquota: '5%' },
  { codigo: '150104', descricao: 'Administracao de Carteiras de Clientes, de Cheques Pre - Datado e Congeneres.', aliquota: '5%' },
  { codigo: '150200', descricao: 'Abertura de Contas em Geral, Inclusive Conta - Corrente, Conta de Investimentos e Aplicacao e Caderneta de Pou - Panca, no Pais e no Exterior, Bem Como A Manutencao Dasreferidas Contas Ativas e Inativas.', aliquota: '5%' },
  { codigo: '150300', descricao: 'Locacao e Manutencao de Cofres Particulares, de Termi - Nais Eletronicos, de Ter Minais de Atendimento e de Bense Equipamentos em Geral.', aliquota: '5%' },
  { codigo: '150400', descricao: 'Fornecimento ou Emissao de Atestados em Geral, Inclusi - VE Atestado de Idoneida De, Atestado de Capacidade FI - Nanceira e Congeneres.', aliquota: '5%' },
  { codigo: '150500', descricao: 'Cadastro, Elaboracao de Ficha Cadastral, Renovacao Cadastral e Congeneres, Inclu Sao ou Exclusao no Cadastro de Emitentes de Cheques Sem Fundos - Ccf ou em Quaisquer Outros Bancos Cadastrais.', aliquota: '5%' },
  { codigo: '150600', descricao: 'Emissao, Reemissao e Fornecimento de Avisos, Comprovan - Tes e Documentos em Gera L, Abono de Firmas, Coleta e Entrega de Documentos, Bens e Valores, Comunicacao Com Outra Agencia ou Com Outra Agencia ou Com A Administracao Central, Licencia - Mento Eletronico de Veiculos, Transferencia de Veiculosagenciamento Fiduciario ou Depositario, D', aliquota: '5%' },
  { codigo: '150700', descricao: 'Acesso, Movimentacao, Atendimento e Consulta A Contas em Geral, Por Qualquer M Eio ou Processo, Inclusive Por Telefone, Fac - Simile, Internet e Telex, Acesso A Termi - Nais de Atendimento, Inclusive 24 Horas, Acesso A Outro Banco e A Rede Compartilhada, Fornecimento de Saldo, Extrato e Demais Informacoes Relativas A', aliquota: '5%' },
  { codigo: '150800', descricao: 'Emissao, Reemissao, Alteracao, Cessao, Substituicao, Cancelamento e Registro de Contrato de Credito, Estudo, Analise e Avaliacao de Operacoes de Credito, Emissao, Con - Cessao, Alteracao ou Contratacao de Aval, Fianca, Anuencia e Congeneres, Servicos Relativos A Abertura de Cre - Dito, Para Quaisquer Fins.', aliquota: '5%' },
  { codigo: '150900', descricao: 'Arrendamento Mercantil (leasing) de Quaisquer Bens, IN - Clusive Cessao de Direit OS e Obrigacoes, Substituicao de Garantia, Alteracao, Cancelamento e Registro de Con - Trato, e Demais Servicos Relacionados AO Arrendamento Mercantil (leasing) .', aliquota: '5%' },
  { codigo: '151000', descricao: 'Servicos Relacionados A Cobrancas, Recebimentos ou Pagamentos em Geral, de Titu Los Quaisquer, de Contas ou Carnes, de Cambio, de Tributos e Por Conta de Terceiros, Inclusive OS Efetuados Por Meio Eletronico, Automatico ou Por Maquinas de Atendimento, Fornecimento de Posicaode Cobranca, Recebimento ou Pagamento, Emi', aliquota: '5%' },
  { codigo: '151100', descricao: 'Devolucao de Titulos, Protesto de Titulos, Sustacao de Protesto, Manutencao de Titulos, Reapresentacao de Titulos, e Demais Servicos A Eles Relacionados.', aliquota: '5%' },
  { codigo: '151200', descricao: 'Custodia em Geral, Inclusive de Titulos e Valores Mobi - Liarios.', aliquota: '5%' },
  { codigo: '151300', descricao: 'Servicos Relacionados A Operacoes de Cambio em Geral, Edicao, Alteracao, Prorr Ogacao, Cancelamento e Baixa Decontrato de Cambio, Emissao de Registro de Exportacao Oude Credito, Cobranca ou Deposito no Exterior, Emissao Fornecimento e Cancelamento de Cheques de Viagem, For - Necimento, Transferencia, Cancelamento e D', aliquota: '5%' },
  { codigo: '151400', descricao: 'Fornecimento, Emissao, Reemissao, Renovacao e Manuten - Cao de Cartao Magnetico, Cartao de Credito, Cartao de Debito, Cartao Salario e Congeneres.', aliquota: '5%' },
  { codigo: '151500', descricao: 'Compensacao de Cheques e Titulos Quaisquer, Servicos Relacionados A Deposito, I Nclusive Deposito Identificado, A Saque de Contas Quaisquer, Por Qualquer Meio ou Pro - Cesso, Inclusive em Terminais Eletronicos e de Atendi - Mento.', aliquota: '5%' },
  { codigo: '151600', descricao: 'Emissao, Reemissao, Liquidacao, Alteracao, Cancelamento e Baixa de Ordens de PA Gamento, Ordens de Credito e Similares, Por Qualquer Meio ou Processo, Servicos Relacionados A Transferencia de Valores, Dados, Fundos, Paga - Mentos e Similares, Inclusive Entre Contas em Geral.', aliquota: '5%' },
  { codigo: '151700', descricao: 'Emissao, Fornecimento, Devolucao, Sustacao, Cancelamentoe Oposicao de Cheques QU Aisquer, Avulso ou Por Talao. Servicos Relacionados A Credito Imobiliario, Avaliacao e Vistoria de Imovel ou Obra, Analise Tecnica e Juridicaemissao, Reemissao,', aliquota: '5%' },
  { codigo: '151800', descricao: 'Alteracao, Transferencia e Renegociacao de Contrato, Emissao e Reemissao do Termo de Quitacao e Demais Servicos Relacionados A Credito Imobilia - Rio.', aliquota: '5%' },
  { codigo: '160101', descricao: 'Transporte de Natureza Municipal.', aliquota: '2%' },
  { codigo: '16010199', descricao: 'Transporte de Natureza Municipal.', aliquota: '0%' },
  { codigo: '160102', descricao: 'Transporte Por Taxi ( Sem Empregados )', aliquota: '2%' },
  { codigo: '16010299', descricao: 'Transporte Por Taxi ( Sem Empregados )', aliquota: '0%' },
  { codigo: '160103', descricao: 'Transporte Por Taxi', aliquota: '2%' },
  { codigo: '16010399', descricao: 'Transporte Por Taxi', aliquota: '0%' },
  { codigo: '160104', descricao: 'Outros Servicos de Transporte de Pessoas e Passageiros', aliquota: '2%' },
  { codigo: '16010499', descricao: 'Outros Servicos de Transporte de Pessoas e Passageiros', aliquota: '0%' },
  { codigo: '160105', descricao: 'Transporte de Veículos', aliquota: '2%' },
  { codigo: '16010599', descricao: 'Transporte de Veículos', aliquota: '0%' },
  { codigo: '160106', descricao: 'Transporte de Mudancas', aliquota: '2%' },
  { codigo: '16010699', descricao: 'Transporte de Mudancas', aliquota: '0%' },
  { codigo: '160107', descricao: 'Transporte de Cargas', aliquota: '2%' },
  { codigo: '16010799', descricao: 'Transporte de Cargas', aliquota: '0%' },
  { codigo: '160108', descricao: 'Transporte de Onibus', aliquota: '2%' },
  { codigo: '16010899', descricao: 'Transporte de Onibus', aliquota: '0%' },
  { codigo: '160109', descricao: 'Transporte de Pequenas Cargas - Carretos', aliquota: '2%' },
  { codigo: '16010999', descricao: 'Transporte de Pequenas Cargas - Carretos', aliquota: '0%' },
  { codigo: '160110', descricao: 'Transporte de Passageiros ( Condutor Escolar )', aliquota: '2%' },
  { codigo: '16011099', descricao: 'Transporte de Passageiros ( Condutor Escolar )', aliquota: '0%' },
  { codigo: '160111', descricao: 'Transporte de Passageiros ( Moto - Taxi ) .', aliquota: '2%' },
  { codigo: '16011199', descricao: 'Transporte de Passageiros ( Moto - Taxi ) .', aliquota: '0%' },
  { codigo: '160112', descricao: 'Transporte de Cargas ( Ponto de Caminhao )', aliquota: '2%' },
  { codigo: '16011299', descricao: 'Transporte de Cargas ( Ponto de Caminhao )', aliquota: '0%' },
  { codigo: '160201', descricao: 'Serviços de Transporte Coletivo Municipal Rodoviário, Metroviário, Ferroviário e Aquaviário de Passageiros', aliquota: '2%' },
  { codigo: '170101', descricao: 'Assessoria de Qualquer Natureza, Não Contida em Outros Itens Desta Lista, Análise, Exame, Pesquisa, Coleta, Compilação e Fornecimento de Dados e Informações de Qualquer Natureza.', aliquota: '4%' },
  { codigo: '17010199', descricao: 'Assessoria de Qualquer Natureza, Nao Contida em Outrositens Desta Lista, Anali Se, Exame, Pesquisa, Coleta, Compilacao e Fornecimento de Dados e Informacoes de Qualquer Natureza.', aliquota: '0%' },
  { codigo: '170102', descricao: 'Consultoria de Qualquer Natureza, Nao Contida em Outrositens Desta Lista, Anali Se, Exame, Pesquisa, Coleta, Compilacao e Fornecimento de Dados', aliquota: '4%' },
  { codigo: '17010299', descricao: 'Consultoria de Qualquer Natureza, Nao Contida em Outrositens Desta Lista, Anali Se, Exame, Pesquisa, Coleta, Compilacao e Fornecimento de Dados', aliquota: '0%' },
  { codigo: '170103', descricao: 'Escrituracao. Cadastro e Congeneres', aliquota: '4%' },
  { codigo: '17010399', descricao: 'Escrituracao. Cadastro e Congeneres', aliquota: '0%' },
  { codigo: '170201', descricao: 'Datilografia (isento)', aliquota: '2.5%' },
  { codigo: '17020199', descricao: 'Datilografia (isento)', aliquota: '0%' },
  { codigo: '170202', descricao: 'Digitacao', aliquota: '2.5%' },
  { codigo: '17020299', descricao: 'Digitacao', aliquota: '0%' },
  { codigo: '170203', descricao: 'Estenografia', aliquota: '2.5%' },
  { codigo: '17020399', descricao: 'Estenografia', aliquota: '0%' },
  { codigo: '170204', descricao: 'Expediente', aliquota: '2.5%' },
  { codigo: '17020499', descricao: 'Expediente', aliquota: '0%' },
  { codigo: '170205', descricao: 'Secretaria em Geral', aliquota: '2.5%' },
  { codigo: '17020599', descricao: 'Secretaria em Geral', aliquota: '0%' },
  { codigo: '170206', descricao: 'Resposta Audivel (telemensagem) .', aliquota: '2.5%' },
  { codigo: '17020699', descricao: 'Resposta Audivel (telemensagem) .', aliquota: '0%' },
  { codigo: '170207', descricao: 'Traducao e Interpretacao', aliquota: '2.5%' },
  { codigo: '17020799', descricao: 'Traducao e Interpretacao', aliquota: '0%' },
  { codigo: '170208', descricao: 'Redacao, Edicao, Revisao, Apoio e Infra - Estrutura Admi - Nistrativa e Congeneres.', aliquota: '2.5%' },
  { codigo: '17020899', descricao: 'Redacao, Edicao, Revisao, Apoio e Infra - Estrutura Admi - Nistrativa e Congeneres.', aliquota: '0%' },
  { codigo: '170301', descricao: 'Planejamento, Coordenacao Tecnica, Financeira ou Admi - Nistrativa.', aliquota: '3.5%' },
  { codigo: '17030199', descricao: 'Planejamento, Coordenacao Tecnica, Financeira ou Admi - Nistrativa.', aliquota: '0%' },
  { codigo: '170302', descricao: 'Programacao, Organizacao Tecnica, Financeira ou Administrativa.', aliquota: '3.5%' },
  { codigo: '170401', descricao: 'Recrutamento de Mao - de - Obra.', aliquota: '3%' },
  { codigo: '170402', descricao: 'Agenciamento, Selecao de Mao - de - Obra.', aliquota: '3%' },
  { codigo: '170403', descricao: 'Colocacao de Mao - de - Obra.', aliquota: '3%' },
  { codigo: '170501', descricao: 'Fornecimento de Mao - de - Obra, Mesmo em Carater Tempora - Rio, Inclusive de Empreg Ados ou Trabalhadores Avulsos ou Temporarios, Contratados Pelo Prestador de Servico.', aliquota: '2.5%' },
  { codigo: '17050199', descricao: 'Fornecimento de Mao - de - Obra, Mesmo em Carater Tempora - Rio, Inclusive de Empreg Ados ou Trabalhadores Avulsos ou Temporarios, Contratados Pelo Prestador de Servico.', aliquota: '0%' },
  { codigo: '170502', descricao: 'Agencias de Recrutamento, Coloc., Selecao e Fornecimentode Mao de Obra.', aliquota: '2.5%' },
  { codigo: '170601', descricao: 'Propaganda e Publicidade.', aliquota: '2%' },
  { codigo: '17060199', descricao: 'Propaganda e Publicidade.', aliquota: '0%' },
  { codigo: '170602', descricao: 'Promocao de Vendas e Negocios', aliquota: '2%' },
  { codigo: '17060299', descricao: 'Promocao de Vendas e Negocios', aliquota: '0%' },
  { codigo: '170603', descricao: 'Planejamento de Campanhas ou Sistemas de Publicidade', aliquota: '2%' },
  { codigo: '17060399', descricao: 'Planejamento de Campanhas ou Sistemas de Publicidade', aliquota: '0%' },
  { codigo: '170604', descricao: 'Elaboracao de Desenhos, Textos e Demais Materiais Publicitarios.', aliquota: '2%' },
  { codigo: '17060499', descricao: 'Elaboracao de Desenhos, Textos e Demais Materiais Publicitarios.', aliquota: '0%' },
  { codigo: '170605', descricao: 'Pesquisa de Mercado', aliquota: '2%' },
  { codigo: '17060599', descricao: 'Pesquisa de Mercado', aliquota: '0%' },
  { codigo: '170800', descricao: 'Franquia (franchising) .', aliquota: '4%' },
  { codigo: '170901', descricao: 'Pericias, Laudos, Exames Tecnicos.', aliquota: '2%' },
  { codigo: '17090199', descricao: 'Pericias, Laudos, Exames Tecnicos.', aliquota: '0%' },
  { codigo: '170902', descricao: 'Analises Tecnicas.', aliquota: '2%' },
  { codigo: '17090299', descricao: 'Analises Tecnicas.', aliquota: '0%' },
  { codigo: '170903', descricao: 'Exames Psicotecnicos', aliquota: '2%' },
  { codigo: '17090399', descricao: 'Exames Psicotecnicos', aliquota: '0%' },
  { codigo: '171001', descricao: 'Planejamento, Organizacao e Administracao de Feiras e Congeneres.', aliquota: '2%' },
  { codigo: '17100199', descricao: 'Planejamento, Organizacao e Administracao de Feiras e Congeneres.', aliquota: '0%' },
  { codigo: '171002', descricao: 'Planejamento, Organizacao e Administracao de Exposicoescongressos e Congeneres.', aliquota: '2%' },
  { codigo: '17100299', descricao: 'Planejamento, Organizacao e Administracao de Exposicoescongressos e Congeneres.', aliquota: '0%' },
  { codigo: '171101', descricao: 'Organizacao de Festas e Recepcoes(exceto O Fornecimen - TO de Alimentacao e Bebi das Que Fica Sujeito AO Icms) .', aliquota: '3%' },
  { codigo: '17110199', descricao: 'Organizacao de Festas e Recepcoes(exceto O Fornecimen - TO de Alimentacao e Bebi das Que Fica Sujeito AO Icms) .', aliquota: '0%' },
  { codigo: '171102', descricao: 'Buffet (exceto O Fornecimento de Alimentacao e Bebidas Que Fica Sujeito AO Icms ) .', aliquota: '3%' },
  { codigo: '171201', descricao: 'Administracao em Geral, Inclusive de Bens e Negocios de Terceiros.', aliquota: '2.5%' },
  { codigo: '17120199', descricao: 'Administracao em Geral, Inclusive de Bens e Negocios de Terceiros.', aliquota: '0%' },
  { codigo: '171202', descricao: 'Administracao de Imoveis', aliquota: '2.5%' },
  { codigo: '17120299', descricao: 'Administracao de Imoveis', aliquota: '0%' },
  { codigo: '171203', descricao: 'Administracao de Empresas', aliquota: '2.5%' },
  { codigo: '17120399', descricao: 'Administracao de Empresas', aliquota: '0%' },
  { codigo: '171204', descricao: 'Administracao de Distribuicao de CO - Seguros.', aliquota: '2.5%' },
  { codigo: '171300', descricao: 'Leilao e Congeneres.', aliquota: '2.5%' },
  { codigo: '17130099', descricao: 'Leilao e Congeneres.', aliquota: '0%' },
  { codigo: '171400', descricao: 'Advocacia.', aliquota: '2%' },
  { codigo: '17140099', descricao: 'Advocacia.', aliquota: '0%' },
  { codigo: '171500', descricao: 'Arbitragem de Qualquer Especie, Inclusive Juridica.', aliquota: '2%' },
  { codigo: '17150099', descricao: 'Arbitragem de Qualquer Especie, Inclusive Juridica.', aliquota: '0%' },
  { codigo: '171600', descricao: 'Auditoria.', aliquota: '2%' },
  { codigo: '17160099', descricao: 'Auditoria.', aliquota: '0%' },
  { codigo: '171700', descricao: 'Analise de Organizacao e Metodos.', aliquota: '2.5%' },
  { codigo: '171800', descricao: 'Atuaria e Calculos Tecnicos de Qualquer Natureza.', aliquota: '2.5%' },
  { codigo: '17180099', descricao: 'Atuaria e Calculos Tecnicos de Qualquer Natureza.', aliquota: '0%' },
  { codigo: '171901', descricao: 'Contabilidade.', aliquota: '2%' },
  { codigo: '17190199', descricao: 'Contabilidade.', aliquota: '0%' },
  { codigo: '171902', descricao: 'Tecnico em Contabilidade', aliquota: '2%' },
  { codigo: '17190299', descricao: 'Tecnico em Contabilidade', aliquota: '0%' },
  { codigo: '172001', descricao: 'Consultoria Economica ou Financeira.', aliquota: '3.5%' },
  { codigo: '17200199', descricao: 'Consultoria Economica ou Financeira.', aliquota: '0%' },
  { codigo: '172002', descricao: 'Assessoria Economica ou Financeira.', aliquota: '3.5%' },
  { codigo: '17200299', descricao: 'Assessoria Economica ou Financeira.', aliquota: '0%' },
  { codigo: '172003', descricao: 'Economista', aliquota: '3.5%' },
  { codigo: '17200399', descricao: 'Economista', aliquota: '0%' },
  { codigo: '172100', descricao: 'Estatistica.', aliquota: '3.5%' },
  { codigo: '17210099', descricao: 'Estatistica.', aliquota: '0%' },
  { codigo: '172201', descricao: 'Cobranca em Geral. ( Cobrador )', aliquota: '3.5%' },
  { codigo: '17220199', descricao: 'Cobranca em Geral. ( Cobrador )', aliquota: '0%' },
  { codigo: '172202', descricao: 'Cobrancas ( Outras Instituicoes )', aliquota: '3.5%' },
  { codigo: '172300', descricao: 'Factoring - Assessoria, Analise, Aval., Atend., Consulta, Cadastro, Selecao, Gerenc. de Informacoes, Admin. Contas A RE - Ceber ou A Pagar e em Geral, Relacionados A Operacoes de Faturizacao.', aliquota: '3.5%' },
  { codigo: '172400', descricao: 'Apresentacao de Palestras, Conferencias, Seminarios e Congeneres.', aliquota: '2%' },
  { codigo: '17240099', descricao: 'Apresentacao de Palestras, Conferencias, Seminarios e Congeneres.', aliquota: '0%' },
  { codigo: '172500', descricao: 'Inserção de Textos, Desenhos e Outros Materiais de Propaganda e Publicidade, em Qualquer Meio (exceto em Livros, Jornais, Periódicos e nas Modalidades de Serviços de Radiodifusão Sonora e de Sons e Imagens de Recepção Livre e Gratuita) .', aliquota: '2%' },
  { codigo: '180101', descricao: 'Regulacao de Sinistros Vinculados A Contratos de Segu - Ros, Inspecao e Avaliaca O de Riscos P/cobertura de Con - Tratos de Seguros, .', aliquota: '2.5%' },
  { codigo: '18010199', descricao: 'Regulacao de Sinistros Vinculados A Contratos de Segu - Ros, Inspecao e Avaliaca O de Riscos P/cobertura de Con - Tratos de Seguros, .', aliquota: '0%' },
  { codigo: '180102', descricao: 'Prevencao e Gerencia de Riscos Seguraveis e Congeneres.', aliquota: '2.5%' },
  { codigo: '190100', descricao: 'Servicos de Distribuicao e Venda de Bilhetes e Demais Produtos de Loteria, Bin Gos, Cartoes, Pules ou Cupons de Apostas, Sorteios, Premios, Inclusive OS Decorrentes de Titulos de Capitalizacao e Congeneres.', aliquota: '0%' },
  { codigo: '19010099', descricao: 'Servicos de Distribuicao e Venda de Bilhetes e Demais Produtos de Loteria, Bin Gos, Cartoes, Pules ou Cupons de Apostas, Sorteios, Premios, Inclusive OS Decorrentes de Titulos de Capitalizacao e Congeneres.', aliquota: '0%' },
  { codigo: '190101', descricao: 'Servicos de Distribuicao e Venda de Bilhetes e Demais Produtos de Loteria, Bingo Cartoes, Pules ou Cupons de Apostas, Sorteios, Premios, Inclusive OS Decorrentes Detitulos de Capitalizacao e Congeneres.', aliquota: '4%' },
  { codigo: '190102', descricao: 'Distribuicao e Venda de Cartelas, Sorteios ou Premios em Bingos, Telebingos e Assemelhados.', aliquota: '4%' },
  { codigo: '200100', descricao: 'Servicos Portuarios, Ferroportuarios, Utilizacao de Porto, Movimentacao de Pass Ageiros, Reboque de Embarcacoesrebocador Escoteiro, Atracacao, Desatracacao, Servicos de Praticagem, Capatazia, Armazenagem de Qualquer Natu - Reza, Servicos Acessorios, Movimentacao de Mercadorias Servicos de Apoio Maritimo, de Movimentac', aliquota: '0%' },
  { codigo: '200200', descricao: 'Servicos Aeroportuarios, Utilizacao de Aeroporto, Movi - Mentacao de Passageiros, Armazenagem de Qualquer Natu - Reza, Capatazia, Movimentacao de Aeronaves, Servicos Deapoio Aeroportuarios, Servicos Acessorios, Movimentacaode Mercadorias, Logistica e Congeneres.', aliquota: '5%' },
  { codigo: '200300', descricao: 'Servicos de Terminais Rodoviarios, Ferroviarios, Metro - Viarios, Movimentacao de Passageiros, Mercadorias, IN - Clusive Suas Operacoes, Logistica e Congeneres.', aliquota: '5%' },
  { codigo: '20100', descricao: 'Servicos de Pesquisas e Desenvolvimento de Qualquer Natureza.', aliquota: '3.5%' },
  { codigo: '2010099', descricao: 'Servicos de Pesquisas e Desenvolvimento de Qualquer Natureza.', aliquota: '0%' },
  { codigo: '210100', descricao: 'Serviços de registros públicos, cartorários e notariais.', aliquota: '2%' },
  { codigo: '220101', descricao: 'Servicos de Exploracao de Rodovia Mediante Cobranca de Preco ou Pedagio dos Usu Arios, Envolvendo Exec. de Serv. de Conservacao, Manut., Melhoramentos P/ Adequa - Cao de Capacidade e Seg. Transito, Oper., Monit., Assist. Usuarios e Outros Serv. Definido em Contrato, Ato Concessao, Permissao ou Normas Oficiais', aliquota: '5%' },
  { codigo: '220102', descricao: 'Servicos Definidos em Contatro - Operacao, Manutencao, Coordenacao, Fornecimento, Fiscalizacao e Instalacao de Equipamentos Estaticos ou Portateis, Fixos ou Nao, de Registro das Infracoes de Excesso de Velocidade, ou de Passagem, em Rodovias.', aliquota: '5%' },
  { codigo: '230100', descricao: 'Servicos de Programacao e Comunicacao Visual, Desenho Industrial e Congeneres.', aliquota: '2%' },
  { codigo: '23010099', descricao: 'Servicos de Programacao e Comunicacao Visual, Desenho Industrial e Congeneres.', aliquota: '0%' },
  { codigo: '240101', descricao: 'Servicos de Chaveiros.', aliquota: '2.5%' },
  { codigo: '24010199', descricao: 'Servicos de Chaveiros.', aliquota: '0%' },
  { codigo: '240102', descricao: 'Servicos de Confeccao de Carimbos.', aliquota: '2.5%' },
  { codigo: '24010299', descricao: 'Servicos de Confeccao de Carimbos.', aliquota: '0%' },
  { codigo: '240103', descricao: 'Servicos de Confeccao de Placas, Sinalizacao Visual, Banners, Adesivos e Cong Eneres.', aliquota: '2.5%' },
  { codigo: '250100', descricao: 'Funerais, Inclusive Fornecimento de Caixao, Urna ou ES - Quifes, Aluguel de Capel A, Transporte do Corpo Cadave - Rico, Fornecimento de Flores, Coroas e Outros Paramen - Tos Desembaraco de Certidao de Obito, Fornecimento de Veu Essa e Outros Adornos, Embalsamento, Embelezamento, Conservacao ou Restauracao de Cadaveres.', aliquota: '4%' },
  { codigo: '250200', descricao: 'Translado Intramunicipal e Cremação de Corpos e Partes de Corpos Cadavéricos.', aliquota: '4%' },
  { codigo: '250300', descricao: 'Planos ou Convenio Funerarios.', aliquota: '4%' },
  { codigo: '250400', descricao: 'Manutencao e Conservacao de Jazigos e Cemiterios.', aliquota: '2%' },
  { codigo: '250500', descricao: 'Cessão de Uso de Espaços em Cemitérios Para Sepultamento.', aliquota: '4%' },
  { codigo: '260101', descricao: 'Servicos de Coleta, Remessa ou Entrega de Correspondencias, Documentos, Objetos ou Bens Pelos Correios e Suas Agencias Franqueadas.', aliquota: '4%' },
  { codigo: '260102', descricao: 'TRANSPORTE DE VALORES, DENTRO DO TERRITORIO DO MUNICIPIO.', aliquota: '4%' },
  { codigo: '260103', descricao: 'Servicos de Coleta, Remessa ou Entrega de Correspondencias, Documentos, Objetos Bens ou Valores, Por Courrier, Moto - Boy ou Congeneres.', aliquota: '4%' },
  { codigo: '26010399', descricao: 'Servicos de Coleta, Remessa ou Entrega de Correspondencias, Documentos, Objetos Bens ou Valores, Por Courrier, Moto - Boy ou Congeneres.', aliquota: '0%' },
  { codigo: '270100', descricao: 'Servicos de Assistencia Social.', aliquota: '2%' },
  { codigo: '27010099', descricao: 'Servicos de Assistencia Social.', aliquota: '0%' },
  { codigo: '280100', descricao: 'Servicos de Avaliacao de Bens e Servicos de Qualquer Natureza.', aliquota: '2%' },
  { codigo: '28010099', descricao: 'Servicos de Avaliacao de Bens e Servicos de Qualquer Natureza.', aliquota: '0%' },
  { codigo: '290100', descricao: 'Servicos de Biblioteconomia.', aliquota: '2%' },
  { codigo: '29010099', descricao: 'Servicos de Biblioteconomia.', aliquota: '0%' },
  { codigo: '300101', descricao: 'Servicos de Biologia.', aliquota: '2%' },
  { codigo: '30010199', descricao: 'Servicos de Biologia.', aliquota: '0%' },
  { codigo: '300102', descricao: 'Servicos de Biotecnologia', aliquota: '2%' },
  { codigo: '30010299', descricao: 'Servicos de Biotecnologia', aliquota: '0%' },
  { codigo: '300103', descricao: 'Servicos de Quimica', aliquota: '2%' },
  { codigo: '30010399', descricao: 'Servicos de Quimica', aliquota: '0%' },
  { codigo: '30100', descricao: 'Locação de Bens Moveis', aliquota: '0%' },
  { codigo: '30200', descricao: 'Cessao de Direito de Uso de Marcas e de Sinais de Propaganda.', aliquota: '2%' },
  { codigo: '30301', descricao: 'Exploracao de Saloes de Festas, Para Realizacao de Eventos ou Negocios de Qualq Uer Natureza.', aliquota: '4%' },
  { codigo: '30302', descricao: 'Exploracao de Centro de Convencoes, Escritorios Virtuaisstands, Para Realizacao D E Eventos ou Negocios de Qualquer Natureza.', aliquota: '4%' },
  { codigo: '30303', descricao: 'Exploracao de Quadras Esportivas, Estadios, Ginasios, Canchas e Congeneres, Par A Realizacao de Eventos ou Negocios de Qualquer Natureza.', aliquota: '4%' },
  { codigo: '30304', descricao: 'Exploracao de Auditorios, Casas de Espetaculos, Para Realizacao de Eventos ou N Egocios de Qualquer Natureza.', aliquota: '4%' },
  { codigo: '30305', descricao: 'Exploracao de Parques de Diversoes, Para Realizacao de Eventos ou Exploracao de Parques de Diversoes, Para Realizacao de Eventos ou Negocios de Qualquer Natureza.', aliquota: '4%' },
  { codigo: '30400', descricao: 'Locacao, Sublocacao, Arrendamento, Direito de Passagem ou Locacao, Sublocacao, Arrendamento, Direito de Passagem ou Permissao de Uso, Com Partilhado ou Nao, de Ferrovia, Rodovia, Postes, Cabos, Dutos e Condutos de Qualquer Natureza.', aliquota: '3.5%' },
  { codigo: '30500', descricao: 'Cessao de Andaimes, Palcos, Coberturas e Outras Estruturas de Uso Temporario.', aliquota: '3.5%' },
  { codigo: '310101', descricao: 'Servicos Tecnicos em Edificacoes', aliquota: '2%' },
  { codigo: '31010199', descricao: 'Servicos Tecnicos em Edificacoes', aliquota: '0%' },
  { codigo: '310102', descricao: 'Servicos Tecnicos em Eletronica.', aliquota: '2%' },
  { codigo: '31010299', descricao: 'Servicos Tecnicos em Eletronica.', aliquota: '0%' },
  { codigo: '310103', descricao: 'Servicos Tecnicos em Eletrotecnica.', aliquota: '2%' },
  { codigo: '31010399', descricao: 'Servicos Tecnicos em Eletrotecnica.', aliquota: '0%' },
  { codigo: '310104', descricao: 'Servicos Tecnicos em Mecanica.', aliquota: '2%' },
  { codigo: '310105', descricao: 'Servicos Tecnicos em Telecomunicacoes e Congeneres.', aliquota: '2%' },
  { codigo: '31010599', descricao: 'Servicos Tecnicos em Telecomunicacoes e Congeneres.', aliquota: '0%' },
  { codigo: '320100', descricao: 'Servicos de Desenhos Tecnicos.', aliquota: '3%' },
  { codigo: '32010099', descricao: 'Servicos de Desenhos Tecnicos.', aliquota: '0%' },
  { codigo: '330100', descricao: 'Servicos de Desembaraco Aduaneiro, Comissarios, Despa - Chantes e Congeneres.', aliquota: '2%' },
  { codigo: '33010099', descricao: 'Servicos de Desembaraco Aduaneiro, Comissarios, Despachantes e Congeneres.', aliquota: '0%' },
  { codigo: '340100', descricao: 'Servicos de Investigacoes Particulares, Detetives e Congeneres.', aliquota: '2.5%' },
  { codigo: '34010099', descricao: 'Servicos de Investigacoes Particulares, Detetives e Congeneres.', aliquota: '0%' },
  { codigo: '350101', descricao: 'Servicos de Reportagem.', aliquota: '2%' },
  { codigo: '35010199', descricao: 'Servicos de Reportagem.', aliquota: '0%' },
  { codigo: '350102', descricao: 'Assessoria de Imprensa', aliquota: '2%' },
  { codigo: '35010299', descricao: 'Assessoria de Imprensa', aliquota: '0%' },
  { codigo: '350103', descricao: 'Jornalismo.', aliquota: '2%' },
  { codigo: '35010399', descricao: 'Jornalismo.', aliquota: '0%' },
  { codigo: '350104', descricao: 'Relacoes Publicas.', aliquota: '2%' },
  { codigo: '35010499', descricao: 'Relacoes Publicas.', aliquota: '0%' },
  { codigo: '350105', descricao: 'Locutor, Apresentador.', aliquota: '2%' },
  { codigo: '35010599', descricao: 'Locutor, Apresentador.', aliquota: '0%' },
  { codigo: '360100', descricao: 'Servicos de Meteorologia.', aliquota: '2.5%' },
  { codigo: '370100', descricao: 'Servicos de Artistas, Atletas, Modelos e Manequins.', aliquota: '0%' },
  { codigo: '37010099', descricao: 'Servicos de Artistas, Atletas, Modelos e Manequins.', aliquota: '0%' },
  { codigo: '370101', descricao: 'Servicos de Artistas.', aliquota: '2%' },
  { codigo: '37010199', descricao: 'Servicos de Artistas.', aliquota: '0%' },
  { codigo: '370102', descricao: 'Servicos de Atletas', aliquota: '2%' },
  { codigo: '37010299', descricao: 'Servicos de Atletas', aliquota: '0%' },
  { codigo: '370103', descricao: 'Servicos de Modelos e Manequins', aliquota: '2%' },
  { codigo: '380100', descricao: 'Servicos de Museologia.', aliquota: '2%' },
  { codigo: '390100', descricao: 'Servicos de Ourivesaria e Lapidacao (quando O Material For Fornecido Pelo Tomad OR do Servico) .', aliquota: '2.5%' },
  { codigo: '39010099', descricao: 'Servicos de Ourivesaria e Lapidacao (quando O Material For Fornecido Pelo Tomad OR do Servico) .', aliquota: '0%' },
  { codigo: '3946000', descricao: 'Deposito Fechado', aliquota: '2%' },
  { codigo: '3970000', descricao: 'Bancos', aliquota: '5%' },
  { codigo: '3970100', descricao: 'Companhias de Seguros', aliquota: '2.5%' },
  { codigo: '3970200', descricao: 'Financeiras, Titulos e Valores', aliquota: '5%' },
  { codigo: '3980000', descricao: 'Empresas de Onibus', aliquota: '2%' },
  { codigo: '3980200', descricao: 'Escolas de Ensino Fundamental ou Medio', aliquota: '2%' },
  { codigo: '3980300', descricao: 'Escolas Pre - Primario, Hospedagem Infantil', aliquota: '2%' },
  { codigo: '3980400', descricao: 'Escola de Modal. Esportivas(natacao, Futebol, Tenis, Etc. . .', aliquota: '2%' },
  { codigo: '3980700', descricao: 'Universidades', aliquota: '2%' },
  { codigo: '3981000', descricao: 'Parque de Diversoes', aliquota: '3.5%' },
  { codigo: '3981300', descricao: 'Emissora de Radio', aliquota: '2%' },
  { codigo: '3981400', descricao: 'Emissora de Televisao', aliquota: '2%' },
  { codigo: '3981500', descricao: 'Garagem', aliquota: '4%' },
  { codigo: '3981600', descricao: 'Transporte de Moto - Taxi', aliquota: '2%' },
  { codigo: '3982000', descricao: 'Engraxataria', aliquota: '0%' },
  { codigo: '3983500', descricao: 'Cartorios, Tabeliaes', aliquota: '2%' },
  { codigo: '3983700', descricao: 'Gravacao e Distribuicao de Filmes Videos Tapes', aliquota: '3%' },
  { codigo: '3983800', descricao: 'Veiculacao de Textos, Des. Outros Mat. Public. P/qqmeio', aliquota: '2%' },
  { codigo: '3983900', descricao: 'Comunic. Telef. de 1p/outro Aparel. (no Mesmo Municipio)', aliquota: '2%' },
  { codigo: '3989900', descricao: 'Empresas de Transporte Aereo', aliquota: '2%' },
  { codigo: '3990000', descricao: 'Empresas de Turismo em Geral', aliquota: '2%' },
  { codigo: '3990100', descricao: 'Transportadoras', aliquota: '2%' },
  { codigo: '3990200', descricao: 'Transporte Rodoviarios de Cargas ( Com Incidencia Iss )', aliquota: '2%' },
  { codigo: '3990500', descricao: 'Outros Escritorios', aliquota: '0%' },
  { codigo: '3990600', descricao: 'Clubes Recreativos e de Servicos', aliquota: '4%' },
  { codigo: '3994400', descricao: 'Editora de Jornais', aliquota: '2%' },
  { codigo: '400100', descricao: 'Obras de Arte Sob Encomenda.', aliquota: '2.5%' },
  { codigo: '40010099', descricao: 'Obras de Arte Sob Encomenda.', aliquota: '0%' },
  { codigo: '40101', descricao: 'Medicina', aliquota: '2%' },
  { codigo: '401011', descricao: '4.01  Medicina e biomedicina.', aliquota: '2%' },
  { codigo: '4010199', descricao: 'Medicina', aliquota: '0%' },
  { codigo: '40102', descricao: 'Medico Residente', aliquota: '2%' },
  { codigo: '4010299', descricao: 'Medico Residente', aliquota: '0%' },
  { codigo: '40103', descricao: 'Biomedicina', aliquota: '2%' },
  { codigo: '4010399', descricao: 'Biomedicina', aliquota: '0%' },
  { codigo: '40201', descricao: 'Analises Clinicas, Patologia. Tecnicos em Analises Clinicas, Eletricidade Medica, Radioterapia, Radiologia', aliquota: '2%' },
  { codigo: '4020199', descricao: 'Analises Clinicas, Patologia. Tecnicos em Analises Clinicas, Eletricidade Medica, Radioterapia, Radiologia', aliquota: '0%' },
  { codigo: '40202', descricao: 'Tecnicos em Analises Clinicas, Eletricidade Medica, Radioterapia, Radiologia', aliquota: '2%' },
  { codigo: '4020299', descricao: 'Tecnicos em Analises Clinicas, Eletricidade Medica, Radioterapia, Radiologia', aliquota: '0%' },
  { codigo: '40203', descricao: 'Eletricidade Medica', aliquota: '2%' },
  { codigo: '40204', descricao: 'Radioterapia, Quimioterapia, Ultra - Sonografia, Ressonancia Magnetica, Radiologi A, Tomografia e Congeneres.', aliquota: '2%' },
  { codigo: '4020499', descricao: 'Radioterapia, Quimioterapia, Ultra - Sonografia, Ressonancia Magnetica, Radiologi A, Tomografia e Congeneres.', aliquota: '0%' },
  { codigo: '40301', descricao: 'Hospitais', aliquota: '2%' },
  { codigo: '40302', descricao: 'Clinicas', aliquota: '2%' },
  { codigo: '403021', descricao: 'Clinicas (Cooperativa)', aliquota: '2%' },
  { codigo: '40303', descricao: 'Laboratorios', aliquota: '2%' },
  { codigo: '40304', descricao: 'Sanatorios', aliquota: '2%' },
  { codigo: '40305', descricao: 'Manicomios', aliquota: '2%' },
  { codigo: '40306', descricao: 'Casas de Saude', aliquota: '2%' },
  { codigo: '40307', descricao: 'Prontos - Socorros', aliquota: '2%' },
  { codigo: '40308', descricao: 'Ambulatorios e Congeneres', aliquota: '2%' },
  { codigo: '40400', descricao: 'Instrumentacao Cirurgica.', aliquota: '2%' },
  { codigo: '4040099', descricao: 'Instrumentacao Cirurgica.', aliquota: '0%' },
  { codigo: '40500', descricao: 'Acupuntura.', aliquota: '2%' },
  { codigo: '4050099', descricao: 'Acupuntura.', aliquota: '0%' },
  { codigo: '40601', descricao: 'Enfermagem.', aliquota: '2%' },
  { codigo: '4060199', descricao: 'Enfermagem.', aliquota: '0%' },
  { codigo: '40602', descricao: 'Atendente de Enfermagem (isento) .', aliquota: '2%' },
  { codigo: '4060299', descricao: 'Atendente de Enfermagem (isento) .', aliquota: '0%' },
  { codigo: '40603', descricao: 'Tecnico em Enfermagem', aliquota: '2%' },
  { codigo: '4060399', descricao: 'Tecnico em Enfermagem', aliquota: '0%' },
  { codigo: '40604', descricao: 'Outros Servicos Auxiliares (enfermagem)', aliquota: '2%' },
  { codigo: '4060499', descricao: 'Outros Servicos Auxiliares (enfermagem)', aliquota: '0%' },
  { codigo: '40700', descricao: 'Servicos Farmaceuticos.', aliquota: '2%' },
  { codigo: '4070099', descricao: 'Servicos Farmaceuticos.', aliquota: '0%' },
  { codigo: '40801', descricao: 'Terapia Ocupacional.', aliquota: '2%' },
  { codigo: '4080199', descricao: 'Terapia Ocupacional.', aliquota: '0%' },
  { codigo: '40802', descricao: 'Fisioterapia', aliquota: '2%' },
  { codigo: '408021', descricao: 'Fisioterapia (Cooperativa)', aliquota: '2%' },
  { codigo: '4080299', descricao: 'Fisioterapia', aliquota: '0%' },
  { codigo: '40803', descricao: 'Fonoaudiologia', aliquota: '2%' },
  { codigo: '4080399', descricao: 'Fonoaudiologia', aliquota: '0%' },
  { codigo: '40900', descricao: 'Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental', aliquota: '2%' },
  { codigo: '4090099', descricao: 'Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental', aliquota: '0%' },
  { codigo: '41000', descricao: 'Nutricao.', aliquota: '2%' },
  { codigo: '4100099', descricao: 'Nutricao.', aliquota: '0%' },
  { codigo: '41100', descricao: 'Obstetricia.', aliquota: '2%' },
  { codigo: '4110099', descricao: 'Obstetricia.', aliquota: '0%' },
  { codigo: '41200', descricao: 'Odontologia.', aliquota: '2%' },
  { codigo: '4120099', descricao: 'Odontologia.', aliquota: '0%' },
  { codigo: '41300', descricao: 'Ortoptica.', aliquota: '2%' },
  { codigo: '4130099', descricao: 'Ortoptica.', aliquota: '0%' },
  { codigo: '41400', descricao: 'Proteses Sob Encomenda.', aliquota: '0%' },
  { codigo: '4140099', descricao: 'Proteses Sob Encomenda.', aliquota: '0%' },
  { codigo: '41401', descricao: 'Protese Dentaria', aliquota: '2%' },
  { codigo: '4140199', descricao: 'Protese Dentaria', aliquota: '0%' },
  { codigo: '41402', descricao: 'Protese Ortopedica', aliquota: '2%' },
  { codigo: '41403', descricao: 'Outras Proteses', aliquota: '2%' },
  { codigo: '41500', descricao: 'Psicanalise.', aliquota: '2%' },
  { codigo: '4150099', descricao: 'Psicanalise.', aliquota: '0%' },
  { codigo: '41600', descricao: 'Psicologia.', aliquota: '2%' },
  { codigo: '416001', descricao: 'Psicologia (Cooperativa)', aliquota: '2%' },
  { codigo: '4160099', descricao: 'Psicologia.', aliquota: '0%' },
  { codigo: '41701', descricao: 'Casas de Repouso e de Recuperacao e Congeneres.', aliquota: '2%' },
  { codigo: '41702', descricao: 'Creches.', aliquota: '2%' },
  { codigo: '41703', descricao: 'Asilos', aliquota: '2%' },
  { codigo: '41800', descricao: 'Inseminacao Artificial, Fertilizacao IN Vitro e Congeneres', aliquota: '2%' },
  { codigo: '41900', descricao: 'Bancos de Sangue, Leite, Pele, Olhos, Ovulos, Semen e Congeneres.', aliquota: '2%' },
  { codigo: '41901', descricao: 'Bancos de Sangue', aliquota: '2%' },
  { codigo: '41902', descricao: 'Banco de Leite', aliquota: '2%' },
  { codigo: '41903', descricao: 'Banco de Pele', aliquota: '2%' },
  { codigo: '41904', descricao: 'Banco de Olhos', aliquota: '2%' },
  { codigo: '41905', descricao: 'Banco de Ovolus e Semen', aliquota: '2%' },
  { codigo: '41906', descricao: 'Banco de Orgaos e Materiais Biologicos de Qualquer Especie', aliquota: '2%' },
  { codigo: '42000', descricao: 'Coleta de Sangue, Leite, Tecidos, Semen, Orgaos e Mate - Riais Biologicos de Qual Quer Especie.', aliquota: '0%' },
  { codigo: '42001', descricao: 'Coleta de Sangue', aliquota: '2%' },
  { codigo: '42002', descricao: 'Coleta de Leite', aliquota: '2%' },
  { codigo: '42003', descricao: 'Coleta de Tecidos', aliquota: '2%' },
  { codigo: '42004', descricao: 'Coleta de Ovolus e Semen', aliquota: '2%' },
  { codigo: '42005', descricao: 'Coleta de Orgaos e Materiais Biologicos de Qualquer Especie', aliquota: '2%' },
  { codigo: '42010', descricao: 'Cooperativas', aliquota: '0%' },
  { codigo: '42100', descricao: 'Unidade de Atendimento, Assistencia ou Tratamento Movele Congeneres.', aliquota: '2%' },
  { codigo: '42200', descricao: 'Planos de Medicina de Grupo ou Individual e Convenios P/ Prestacao de Assisten Cia Medica, Hospitalar, Odonto Logica e Congeneres.', aliquota: '2%' },
  { codigo: '42300', descricao: 'Outros Planos de Saude Que SE Cumpram Atraves de Servi - Cos de Terceiros Contrat Ados, Credenciados, Cooperados Ouapenas Pagos Pelo Operador do Plano Mediante Indicacao do Beneficiario.', aliquota: '2%' },
  { codigo: '50101', descricao: 'Medicina Veterinaria', aliquota: '2%' },
  { codigo: '5010199', descricao: 'Medicina Veterinaria', aliquota: '0%' },
  { codigo: '50102', descricao: 'Zootecnia.', aliquota: '2%' },
  { codigo: '5010299', descricao: 'Zootecnia.', aliquota: '0%' },
  { codigo: '50200', descricao: 'Hospitais, Clinicas, Ambulatorios, Prontos - Socorros e Congeneres, Hospitais, Clinicas, Ambulatorios, Prontos - Socorros e Congeneres, na Area Vete Rinaria.', aliquota: '3%' },
  { codigo: '50300', descricao: 'Laboratorios de Analise na Area Veterinaria.', aliquota: '2.5%' },
  { codigo: '50400', descricao: 'Inseminacao Artificial, Fertilizacao IN Vitro e Congeneres, na Area Veterinari A.', aliquota: '2.5%' },
  { codigo: '50500', descricao: 'Bancos de Sangue e de Orgaos e Congeneres, na Area Veterinaria.', aliquota: '2.5%' },
  { codigo: '50600', descricao: 'Coleta de Sangue, Leite, Tecidos, Semen, Orgaos e Mate Riais Biologicos de Qual Q. Especie, na Area Veterinaria', aliquota: '2.5%' },
  { codigo: '50700', descricao: 'Unidade de Atendimento, Assistencia ou Tratamento Movel e Congeneres, na Area V Eterinaria.', aliquota: '2.5%' },
  { codigo: '50801', descricao: 'Guarda, Alojamento e Congeneres, de Animais.', aliquota: '2.5%' },
  { codigo: '50802', descricao: 'Tratamento de Animais', aliquota: '2.5%' },
  { codigo: '5080299', descricao: 'Tratamento de Animais', aliquota: '0%' },
  { codigo: '50803', descricao: 'Amestramento', aliquota: '2.5%' },
  { codigo: '5080399', descricao: 'Amestramento', aliquota: '0%' },
  { codigo: '50804', descricao: 'Embelezamento de Animais', aliquota: '2.5%' },
  { codigo: '5080499', descricao: 'Embelezamento de Animais', aliquota: '0%' },
  { codigo: '50900', descricao: 'Planos de Atendimento e Assistencia Medico - Veterinaria.', aliquota: '2.5%' },
  { codigo: '60101', descricao: 'Barbearia', aliquota: '2%' },
  { codigo: '6010199', descricao: 'Barbearia', aliquota: '0%' },
  { codigo: '60102', descricao: 'Cabeleireiros', aliquota: '2%' },
  { codigo: '6010299', descricao: 'Cabeleireiros', aliquota: '0%' },
  { codigo: '60103', descricao: 'Manicuros', aliquota: '2%' },
  { codigo: '6010399', descricao: 'Manicuros', aliquota: '0%' },
  { codigo: '60104', descricao: 'Manicuros', aliquota: '2%' },
  { codigo: '60105', descricao: 'Pedicuros', aliquota: '2%' },
  { codigo: '6010599', descricao: 'Pedicuros', aliquota: '0%' },
  { codigo: '60106', descricao: 'Pedicuros', aliquota: '2%' },
  { codigo: '60201', descricao: 'Esteticistas, Tratamento de Pele.', aliquota: '2.5%' },
  { codigo: '6020199', descricao: 'Esteticistas, Tratamento de Pele.', aliquota: '0%' },
  { codigo: '60202', descricao: 'Depilacao, Embelezamento e Congeneres.', aliquota: '2.5%' },
  { codigo: '6020299', descricao: 'Depilacao, Embelezamento e Congeneres.', aliquota: '0%' },
  { codigo: '60203', descricao: 'Aplicacao de Tatuagem, Piercing e Congeneres', aliquota: '2.5%' },
  { codigo: '6020399', descricao: 'Aplicacao de Tatuagem, Piercing e Congeneres', aliquota: '0%' },
  { codigo: '60301', descricao: 'Banhos, Duchas, Sauna, e Congeneres.', aliquota: '2.5%' },
  { codigo: '6030199', descricao: 'Banhos, Duchas, Sauna, e Congeneres.', aliquota: '0%' },
  { codigo: '60302', descricao: 'Massagens.', aliquota: '2.5%' },
  { codigo: '6030299', descricao: 'Massagens.', aliquota: '0%' },
  { codigo: '60401', descricao: 'Ginastica e Demais Atividades Fisicas.', aliquota: '3%' },
  { codigo: '6040199', descricao: 'Ginastica e Demais Atividades Fisicas.', aliquota: '0%' },
  { codigo: '60402', descricao: 'Danca', aliquota: '3%' },
  { codigo: '6040299', descricao: 'Danca', aliquota: '0%' },
  { codigo: '60403', descricao: 'Outros Esportes', aliquota: '3%' },
  { codigo: '6040399', descricao: 'Outros Esportes', aliquota: '0%' },
  { codigo: '60404', descricao: 'Natacao', aliquota: '3%' },
  { codigo: '60405', descricao: 'Artes Marciais', aliquota: '3%' },
  { codigo: '6040599', descricao: 'Artes Marciais', aliquota: '0%' },
  { codigo: '60406', descricao: 'Futebol', aliquota: '3%' },
  { codigo: '6040699', descricao: 'Futebol', aliquota: '0%' },
  { codigo: '60407', descricao: 'Tenis', aliquota: '3%' },
  { codigo: '6040799', descricao: 'Tenis', aliquota: '0%' },
  { codigo: '60408', descricao: 'Personal Trainer', aliquota: '3%' },
  { codigo: '6040899', descricao: 'Personal Trainer', aliquota: '0%' },
  { codigo: '60500', descricao: 'Centros de Emagrecimento, Spa e Congeneres.', aliquota: '2.5%' },
  { codigo: '620101', descricao: 'Gravacao e Distribuicao de Filmes e Vedeo - Tapes', aliquota: '3%' },
  { codigo: '70101', descricao: 'Engenharia Civil', aliquota: '2%' },
  { codigo: '7010199', descricao: 'Engenharia Civil', aliquota: '0%' },
  { codigo: '70102', descricao: 'Agronomia e Agrimensura', aliquota: '2%' },
  { codigo: '7010299', descricao: 'Agronomia e Agrimensura', aliquota: '0%' },
  { codigo: '70103', descricao: 'Arquitetura', aliquota: '2%' },
  { codigo: '7010399', descricao: 'Arquitetura', aliquota: '0%' },
  { codigo: '70104', descricao: 'Geologia', aliquota: '2%' },
  { codigo: '7010499', descricao: 'Geologia', aliquota: '0%' },
  { codigo: '70105', descricao: 'Urbanismo', aliquota: '2%' },
  { codigo: '7010599', descricao: 'Urbanismo', aliquota: '0%' },
  { codigo: '70106', descricao: 'Paisagismo e Congeneres', aliquota: '2%' },
  { codigo: '7010699', descricao: 'Paisagismo e Congeneres', aliquota: '0%' },
  { codigo: '70107', descricao: 'Outras Engenharias', aliquota: '2%' },
  { codigo: '7010799', descricao: 'Outras Engenharias', aliquota: '0%' },
  { codigo: '70201', descricao: 'Execucao, Por Administracao, Empreitada ou Subempreita Da, de Obras de Construc AO Civil, (exceto O Fornec. Mer - Cadorias Produzidas Pelo Prestador de Servicos, Fora Dolocal da Prest. Servicos, Que Fica Sujeito AO Icms) .', aliquota: '2%' },
  { codigo: '70202', descricao: 'Execucao de Obras Hidraulicas, e de Outras Semelhantes', aliquota: '2%' },
  { codigo: '70203', descricao: 'Execucao de Obras Eletricas e Outras Obras Semelhantes', aliquota: '2%' },
  { codigo: '70204', descricao: 'Sondagem, Perfuracao de Pocos, Escavacao, Drenagem e Irrigacao', aliquota: '2%' },
  { codigo: '70205', descricao: 'Execucao de Obras de Terraplanagem, Pavimentacao.', aliquota: '2%' },
  { codigo: '70206', descricao: 'Instalacao e Montagem de Produtos, Pecas e Equipamentos ( Construcao Civil )', aliquota: '2%' },
  { codigo: '7020699', descricao: 'Instalacao e Montagem de Produtos, Pecas e Equipamentos ( Construcao Civil )', aliquota: '0%' },
  { codigo: '70207', descricao: 'Execucao de Obras de Telecomunicacoes', aliquota: '2%' },
  { codigo: '70208', descricao: 'Execucao de Edificacoes em Geral', aliquota: '2%' },
  { codigo: '70209', descricao: 'Execucao de Pre - Moldados, Obras C/pre Moldados QQ Natur.', aliquota: '2%' },
  { codigo: '70210', descricao: 'Concretagem', aliquota: '2%' },
  { codigo: '702101', descricao: 'Concretagem (Dedução Livre)', aliquota: '2%' },
  { codigo: '70211', descricao: 'Execucao de Obras de Arte Especiais ( Pontes, Viadutos, Tuneis. )', aliquota: '2%' },
  { codigo: '70212', descricao: 'Execucao de Estruturas em Geral', aliquota: '2%' },
  { codigo: '70213', descricao: 'Servicos Complem. Execucao de Alambrados, Cercas, Redes de Protecao, Telas', aliquota: '2%' },
  { codigo: '70214', descricao: 'Impermeabilizacoes e Isolamentos', aliquota: '2%' },
  { codigo: '7021499', descricao: 'Impermeabilizacoes e Isolamentos', aliquota: '0%' },
  { codigo: '70215', descricao: 'Servicos de Pedreiro', aliquota: '2%' },
  { codigo: '7021599', descricao: 'Servicos de Pedreiro', aliquota: '0%' },
  { codigo: '70216', descricao: 'Servicos de Encanador', aliquota: '2%' },
  { codigo: '7021699', descricao: 'Servicos de Encanador', aliquota: '0%' },
  { codigo: '70217', descricao: 'Servicos de Eletricista', aliquota: '2%' },
  { codigo: '7021799', descricao: 'Servicos de Eletricista', aliquota: '0%' },
  { codigo: '70218', descricao: 'Servicos de Pintor', aliquota: '2%' },
  { codigo: '7021899', descricao: 'Servicos de Pintor', aliquota: '0%' },
  { codigo: '70219', descricao: 'Servicos de Calheiro', aliquota: '2%' },
  { codigo: '7021999', descricao: 'Servicos de Calheiro', aliquota: '0%' },
  { codigo: '70220', descricao: 'Servicos de Armador ( Ferreiro )', aliquota: '2%' },
  { codigo: '7022099', descricao: 'Servicos de Armador ( Ferreiro )', aliquota: '0%' },
  { codigo: '70221', descricao: 'Servicos de Instalacao ou Montagem de Antena Externa, Cabo ou Satelite, Para Televisao, Internet ou Congenere', aliquota: '2%' },
  { codigo: '70222', descricao: 'Servicos de Instalacao ou Montagem de Toldos ou Congeneres, Fixos ou Provisorios', aliquota: '2%' },
  { codigo: '7022299', descricao: 'Servicos de Instalacao ou Montagem de Toldos ou Congeneres, Fixos ou Provisorios', aliquota: '0%' },
  { codigo: '70223', descricao: 'Servicos de Instalacao ou Montagem de AR Condicionado ou Congenere', aliquota: '2%' },
  { codigo: '70224', descricao: 'Servicos de Eletricista (alarmes e Sistemas de Seguranca)', aliquota: '2%' },
  { codigo: '7022499', descricao: 'Servicos de Eletricista (alarmes e Sistemas de Seguranca)', aliquota: '0%' },
  { codigo: '70225', descricao: 'Montagem de Elevadores, Escadas e Esteiras Rolantes.', aliquota: '2%' },
  { codigo: '70226', descricao: 'Instalacao e Montagem de Aparelhos e Centrais de AR Condicionado, Refrigeracao ou Ventilacao', aliquota: '2%' },
  { codigo: '7022699', descricao: 'Instalacao e Montagem de Aparelhos e Centrais de AR Condicionado, Refrigeracao ou Ventilacao', aliquota: '0%' },
  { codigo: '70227', descricao: 'Execucao de Cozinhas Planejadas ou Outros Ambientes, Modulados ou Nao', aliquota: '2%' },
  { codigo: '70228', descricao: 'Execucao de Consultorios Planejados, Modulados ou Nao.', aliquota: '2%' },
  { codigo: '70229', descricao: 'Instalacao e Montagem de Mobiliario Para Estabelecimentos (aparelhados ou Nao de Equipamentos Tais Como Balcoes Refrigerados ou Aquecidos)', aliquota: '2%' },
  { codigo: '70300', descricao: 'Elaboracao de Planos Diretores, Estudos de Viabilidade, Estudos Organizacionais e Outros, Relacionados Com Obrase Servicos de Engenharia, Elaboracao de Anteprojetos, Projetos Basicos e Projetos Executivos Para Trabalhos de Engenharia.', aliquota: '3%' },
  { codigo: '7030099', descricao: 'Elaboracao de Planos Diretores, Estudos de Viabilidade, Estudos Organizacionais e Outros, Relacionados Com Obrase Servicos de Engenharia, Elaboracao de Anteprojetos, Projetos Basicos e Projetos Executivos Para Trabalhos de Engenharia.', aliquota: '0%' },
  { codigo: '70400', descricao: 'Demolicao.', aliquota: '2%' },
  { codigo: '70501', descricao: 'Reparacao, Conservacao e Reforma de Edificios, (exceto O Fornecimento de Mercad Orias Produzidas Pelo Prest. Servicos, Fora do Local da Prest. dos Servicos, Que Fica Sujeito AO Icms) .', aliquota: '2%' },
  { codigo: '70502', descricao: 'Reparacao, Conservacao e Reforma de Estradas, Pontes, Portos e Congeneres (exc Eto O Fornecimento de Mercado Rias Produzidas Pelo Prest. Servicos, Fora do Local da Prest. dos Servicos, Que Fica Sujeito AO Icms) .', aliquota: '2%' },
  { codigo: '70503', descricao: 'Execucao de Obras P/sinalizacao e Complem. P/sistema Viario.', aliquota: '2%' },
  { codigo: '70601', descricao: 'Colocacao e Instalacao de Tapetes, Com Material Fornecido Pelo Tomador do Servi Co.', aliquota: '2.5%' },
  { codigo: '7060199', descricao: 'Colocacao e Instalacao de Tapetes, Com Material Fornecido Pelo Tomador do Servi Co.', aliquota: '0%' },
  { codigo: '70602', descricao: 'Colocacao e Instal. de Carpetes, Assoalhos, Revestimen - Tos de Parede, Pedras e Outros Revest., Com Material Fornecido Pelo Tomador do Servico.', aliquota: '2.5%' },
  { codigo: '7060299', descricao: 'Colocacao e Instal. de Carpetes, Assoalhos, Revestimen - Tos de Parede, Pedras e Outros Revest., Com Material Fornecido Pelo Tomador do Servico.', aliquota: '0%' },
  { codigo: '70603', descricao: 'Colocacao e Instalacao de Cortinas, Com Material Forne - Cido Pelo Tomador do Ser Vico.', aliquota: '2.5%' },
  { codigo: '7060399', descricao: 'Colocacao e Instalacao de Cortinas, Com Material Forne - Cido Pelo Tomador do Ser Vico.', aliquota: '0%' },
  { codigo: '70604', descricao: 'Colocacao e Instalacao de Vidros, Com Material Forneci - do Pelo Tomador do Servi Co.', aliquota: '2.5%' },
  { codigo: '7060499', descricao: 'Colocacao e Instalacao de Vidros, Com Material Forneci - do Pelo Tomador do Servi Co.', aliquota: '0%' },
  { codigo: '70605', descricao: 'Colocacao e Instalacao de Divisorias, Forros. ., Com Material Fornecido Pelo Toma Dor do Servico.', aliquota: '2.5%' },
  { codigo: '7060599', descricao: 'Colocacao e Instalacao de Divisorias, Forros. ., Com Material Fornecido Pelo Toma Dor do Servico.', aliquota: '0%' },
  { codigo: '70606', descricao: 'Colocacao e Instalacao de Placas de Gesso e Congeneres, Com Material Fornecido Pelo Tomador do Servico.', aliquota: '2.5%' },
  { codigo: '7060699', descricao: 'Colocacao e Instalacao de Placas de Gesso e Congeneres, Com Material Fornecido Pelo Tomador do Servico.', aliquota: '0%' },
  { codigo: '70607', descricao: 'Servico de Marmoreiro', aliquota: '2.5%' },
  { codigo: '70701', descricao: 'Recuperacao, Raspagem de Pisos e Congeneres.', aliquota: '3%' },
  { codigo: '7070199', descricao: 'Recuperacao, Raspagem de Pisos e Congeneres.', aliquota: '0%' },
  { codigo: '70702', descricao: 'Polimento de Pisos e Congeneres.', aliquota: '3%' },
  { codigo: '70703', descricao: 'Lustracao de Pisos e Congeneres.', aliquota: '3%' },
  { codigo: '7070399', descricao: 'Lustracao de Pisos e Congeneres.', aliquota: '0%' },
  { codigo: '70800', descricao: 'Calafetacao.', aliquota: '2.5%' },
  { codigo: '70901', descricao: 'Varricao de Lixo, Rejeitos e Outros Residuos Quaisquer.', aliquota: '3.5%' },
  { codigo: '70902', descricao: 'Coleta de Lixo, Rejeitos e Outros Residuos Quaisquer.', aliquota: '3.5%' },
  { codigo: '70903', descricao: 'Coleta de Entulhos - Cacamba', aliquota: '3.5%' },
  { codigo: '70904', descricao: 'Remocao, Incineracao de Lixo, Rejeitos e Outros Residuosquaisquer.', aliquota: '3.5%' },
  { codigo: '70905', descricao: 'Tratamento, Reciclagem, Separacao e Destinacao Final de Lixo, Rejeitos e Outros Residuos Quaisquer.', aliquota: '3.5%' },
  { codigo: '71001', descricao: 'Limpeza, Manutencao e Conservacao de Vias e Logradouros Publicos', aliquota: '2%' },
  { codigo: '7100199', descricao: 'Limpeza, Manutencao e Conservacao de Vias e Logradouros Publicos', aliquota: '0%' },
  { codigo: '71002', descricao: 'Limpeza, Manutencao e Conservacao de Piscinas.', aliquota: '2%' },
  { codigo: '7100299', descricao: 'Limpeza, Manutencao e Conservacao de Piscinas.', aliquota: '0%' },
  { codigo: '71003', descricao: 'Limpeza, Manutencao e Conservacao de Imoveis, Estruturas, Tanques, Chamines, Dutos, e Congeneres, Por Metodo Mecanico, Quimico, Abrasivo ou Outro.', aliquota: '2%' },
  { codigo: '7100399', descricao: 'Limpeza, Manutencao e Conservacao de Imoveis, Estruturas, Tanques, Chamines, Dutos, e Congeneres, Por Metodo Mecanico, Quimico, Abrasivo ou Outro.', aliquota: '0%' },
  { codigo: '71004', descricao: 'Desentupidora de Esgotos, Fossas e Congeneres.', aliquota: '2%' },
  { codigo: '7100499', descricao: 'Desentupidora de Esgotos, Fossas e Congeneres.', aliquota: '0%' },
  { codigo: '71101', descricao: 'Decoracao.', aliquota: '2%' },
  { codigo: '7110199', descricao: 'Decoracao.', aliquota: '0%' },
  { codigo: '71102', descricao: 'Jardinagem, Inclusive Corte e Poda de Arvores', aliquota: '2%' },
  { codigo: '7110299', descricao: 'Jardinagem, Inclusive Corte e Poda de Arvores', aliquota: '0%' },
  { codigo: '71103', descricao: 'Jardineiro', aliquota: '2%' },
  { codigo: '7110399', descricao: 'Jardineiro', aliquota: '0%' },
  { codigo: '71200', descricao: 'Controle e Tratamento de Efluentes de Qualquer Natureza e de Agentes Fisicos, Q Uimicos e Biologicos.', aliquota: '4%' },
  { codigo: '71301', descricao: 'Dedetizacao, Desinsetizacao, Imunizacao, Desratizacao, Pulverizacao e Congenere S.', aliquota: '2%' },
  { codigo: '7130199', descricao: 'Dedetizacao, Desinsetizacao, Imunizacao, Desratizacao, Pulverizacao e Congenere S.', aliquota: '0%' },
  { codigo: '71302', descricao: 'Desinfeccao', aliquota: '2%' },
  { codigo: '71303', descricao: 'Higienizacao', aliquota: '2%' },
  { codigo: '7130399', descricao: 'Higienizacao', aliquota: '0%' },
  { codigo: '71304', descricao: 'Pulverizacao Aerea', aliquota: '2%' },
  { codigo: '71400', descricao: 'Tratamento de Esgoto', aliquota: '0%' },
  { codigo: '71601', descricao: 'Florestamento', aliquota: '3%' },
  { codigo: '71602', descricao: 'Reflorestamento, Semeadura, Adubação, Reparação de Solo, Plantio, Silagem, Colheita, Corte e Descascamento de Árvores, Silvicultura, Exploração Florestal e dos Serviços Congêneres Indissociáveis da Formação, Manutenção e Colheita de Florestas, Para Quaisquer Fins e Por Quaisquer Meios.', aliquota: '3%' },
  { codigo: '71603', descricao: 'Mecanizacao Agricola', aliquota: '3%' },
  { codigo: '71604', descricao: 'Aviacao Agricola', aliquota: '3%' },
  { codigo: '71700', descricao: 'Escoramento, Contencao de Encostas e Servic. Congeneres', aliquota: '2.5%' },
  { codigo: '71800', descricao: 'Limpeza e Dragagem de Rios, Portos, Canais, Baias, Lagoslagoas, Represas, Acudes e Congeneres.', aliquota: '2.5%' },
  { codigo: '71900', descricao: 'Acompanhamento e Fiscalizacao da Execucao de Obras de Engenharia, Arquitetura e Urbanismo.', aliquota: '2%' },
  { codigo: '7190099', descricao: 'Acompanhamento e Fiscalizacao da Execucao de Obras de Engenharia, Arquitetura e Urbanismo.', aliquota: '0%' },
  { codigo: '72001', descricao: 'Aerofotogrametria (inclusive Interpretacao) .', aliquota: '2.5%' },
  { codigo: '72002', descricao: 'Cartografia, Mapeamento.', aliquota: '2.5%' },
  { codigo: '72003', descricao: 'Levantamentos Topograficos, Batimetricos, Geograficos, Geodesicos, Geologicos, Geofisicos e Congeneres.', aliquota: '2.5%' },
  { codigo: '7200399', descricao: 'Levantamentos Topograficos, Batimetricos, Geograficos, Geodesicos, Geologicos, Geofisicos e Congeneres.', aliquota: '0%' },
  { codigo: '72100', descricao: 'Pesquisa, Perfuracao, Cimentacao, Mergulho, Perfilagem, Concretacao, Testemunhag Em, Pescaria, Estimulacao e ou - Tros Servicos Relacionados C/a Exploracao e Explotacao de Petroleo, Gas Natural e de Outros Recursos Minerais.', aliquota: '3%' },
  { codigo: '72200', descricao: 'Nucleacao e Bombardeamento de Nuvens e Congeneres.', aliquota: '3%' },
  { codigo: '80101', descricao: 'Ensino Fundamental', aliquota: '2%' },
  { codigo: '80102', descricao: 'Ensino Regular Pre - Escolar.', aliquota: '2%' },
  { codigo: '80103', descricao: 'Professor Particular', aliquota: '2%' },
  { codigo: '8010399', descricao: 'Professor Particular', aliquota: '0%' },
  { codigo: '80104', descricao: 'Ensino Medio', aliquota: '2%' },
  { codigo: '80105', descricao: 'Ensino Superior, Sequencial, Pos - Graduacao', aliquota: '2%' },
  { codigo: '80201', descricao: 'Instrucao, Treinamento, Avaliacao de Conhecimentos de Qualquer Natureza.', aliquota: '2%' },
  { codigo: '8020199', descricao: 'Instrucao, Treinamento, Avaliacao de Conhecimentos de Qualquer Natureza.', aliquota: '0%' },
  { codigo: '80202', descricao: 'Escola, Preparacao P/cursos Superiores, Cursinhos.', aliquota: '2%' },
  { codigo: '80203', descricao: 'Ensino de Escola de Cabeleireiros e Congeneres', aliquota: '2%' },
  { codigo: '80204', descricao: 'Ensino de Linguas.', aliquota: '2%' },
  { codigo: '8020499', descricao: 'Ensino de Linguas.', aliquota: '0%' },
  { codigo: '80205', descricao: 'Ensino de Musica, Violao, Piano, Etc.', aliquota: '2%' },
  { codigo: '8020599', descricao: 'Ensino de Musica, Violao, Piano, Etc.', aliquota: '0%' },
  { codigo: '80206', descricao: 'Ensino de Arte Culinaria, Costura, Educacao Artistica, Artesanato, Etc', aliquota: '2%' },
  { codigo: '8020699', descricao: 'Ensino de Arte Culinaria, Costura, Educacao Artistica, Artesanato, Etc', aliquota: '0%' },
  { codigo: '80207', descricao: 'Treinamento, Instrucao na Area de Informatica.', aliquota: '2%' },
  { codigo: '8020799', descricao: 'Treinamento, Instrucao na Area de Informatica.', aliquota: '0%' },
  { codigo: '80208', descricao: 'Orientacao Pedagogica e Educacional', aliquota: '2%' },
  { codigo: '8020899', descricao: 'Orientacao Pedagogica e Educacional', aliquota: '0%' },
  { codigo: '80209', descricao: 'Auto Escola', aliquota: '2%' },
  { codigo: '8020999', descricao: 'Auto Escola', aliquota: '0%' },
  { codigo: '80210', descricao: 'Moto Escola', aliquota: '2%' },
  { codigo: '8299799', descricao: 'Outras atividades de serviços prestados principalmente às empresas não especificadas anteriormente', aliquota: '5%' },
  { codigo: '850100', descricao: 'Veiculacao de Textos, Des. e Outros Mat. Public. P/qq. Meio', aliquota: '2%' },
  { codigo: '850200', descricao: 'Divulgacao de Textos, Des. e Outros Mat. Public. P/qq. Meio', aliquota: '2%' },
  { codigo: '90101', descricao: 'Hospedagem de Qualquer Natureza em Hoteis, (O Valor Daalimentacao e Gorjeta, Q Uando Incluido no Preco da Dia - Ria, Fica Sujeito AO Iss)', aliquota: '4%' },
  { codigo: '90102', descricao: 'Hospedagem em Apart - Service Condominiais, Flat, Apart - Hoteis, Hoteis Residenci A, Residence - Service, Suite Service, (O Valor da Alimentacao e Gorjeta) .', aliquota: '4%' },
  { codigo: '90103', descricao: 'Hotelaria Maritima', aliquota: '4%' },
  { codigo: '90104', descricao: 'Moteis', aliquota: '4%' },
  { codigo: '90105', descricao: 'Hospedagem em Pensoes, Albergues, Pousadas, Hospedarias e Congeneres.', aliquota: '4%' },
  { codigo: '90106', descricao: 'Ocupacao Por Temporada Com Fornecimento de Servico.', aliquota: '4%' },
  { codigo: '90107', descricao: 'Hospedagem Infantil', aliquota: '4%' },
  { codigo: '90200', descricao: 'Agenciamento, Organizacao, Promocao, Intermediacao e Exec. de Programas de Turismo, Passeios, Viagens, Excursoes, Hospedagem e Congeneres.', aliquota: '2%' },
  { codigo: '9020099', descricao: 'Agenciamento, Organizacao, Promocao, Intermediacao e Exec. de Programas de Turismo, Passeios, Viagens, Excursoes, Hospedagem e Congeneres.', aliquota: '0%' },
  { codigo: '90300', descricao: 'Guias de Turismo.', aliquota: '2%' },
  { codigo: '9030099', descricao: 'Guias de Turismo.', aliquota: '0%' },
  { codigo: '970100', descricao: 'Comunic. Telef. de um P/outro Aparelh. (no Mesmo Municip. )', aliquota: '2%' },
];

export function searchAtividadeMunicipal(query: string): AtividadeMunicipal[] {
  const q = query.toLowerCase();
  return ATIVIDADES_MUNICIPAIS.filter(a => a.codigo.includes(q) || a.descricao.toLowerCase().includes(q));
}

